# Generated by Django 5.2.1 on 2025-10-06 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolInstallationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("error", "Error")],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ToolDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the tool, e.g., 'apple-mcp'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly name, e.g., 'Apple MCP'.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of what the tool does.",
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an internal tool (Python, Shell), False for external MCP tools.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Globally enable or disable this tool for all agents.",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP Socket (HTTP/S)"),
                            ("stdin_stdout", "Standard I/O (stdin/stdout)"),
                        ],
                        default="tcp",
                        help_text="The communication transport type for this tool.",
                        max_length=20,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("shared", "Shared Process"),
                            ("dedicated", "Dedicated Process per Instance"),
                        ],
                        default="shared",
                        help_text="Determines if one process is shared across a system or if each agent instance gets a dedicated process.",
                        max_length=20,
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        blank=True,
                        help_text="The Git repository URL for external tools.",
                        null=True,
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True,
                        help_text="The parsed manifest.json file from the repository.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("updating", "Updating"),
                            ("up_to_date", "Up to Date"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "manifest_version",
                    models.CharField(
                        blank=True,
                        help_text="The version from the tool's manifest file.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the manifest was last checked for updates.",
                        null=True,
                    ),
                ),
                (
                    "available_on_all_systems",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this tool is available on all compatible systems by default.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_on_systems",
                    models.ManyToManyField(
                        blank=True,
                        help_text="A specific list of systems where this tool is available.",
                        related_name="tool_definitions",
                        to="systems.system",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolInstallation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_installed", "Not Installed"),
                            ("installing", "Installing"),
                            ("installed", "Installed"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="not_installed",
                        max_length=20,
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        help_text="The installation path on the remote system.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "process_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The PID of the running tool process on the remote system.",
                        null=True,
                    ),
                ),
                (
                    "assigned_port",
                    models.IntegerField(
                        blank=True,
                        help_text="The network port assigned to the running service.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific agent instance this installation is dedicated to. Null for shared tools.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_installations",
                        to="agents.agentinstance",
                    ),
                ),
            ],
        ),
    ]
