# Generated by Django 5.2.7 on 2025-12-03 06:30

import dirtyfields.dirtyfields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the tool, e.g., 'apple-mcp'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly name, e.g., 'Apple MCP'.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of what the tool does.",
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an internal tool (Python, Shell), False for external MCP tools.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Globally enable or disable this tool for all agents.",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP Socket (HTTP/S)"),
                            ("stdin_stdout", "Standard I/O (stdin/stdout)"),
                        ],
                        default="stdin_stdout",
                        help_text="The communication transport type for this tool.",
                        max_length=20,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("shared", "Shared Process"),
                            ("dedicated", "Dedicated Process per Instance"),
                        ],
                        default="shared",
                        help_text="Determines if one process is shared across a system or if each agent instance gets a dedicated process.",
                        max_length=20,
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        blank=True,
                        help_text="The repository URL or PATH for external tools., path begins with file://",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("updating", "Updating"),
                            ("up_to_date", "Up to Date"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "manifest_version",
                    models.CharField(
                        blank=True,
                        help_text="The version from the tool's manifest file.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the manifest was last checked for updates.",
                        null=True,
                    ),
                ),
                (
                    "available_on_all_systems",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this tool is available on all compatible systems by default.",
                    ),
                ),
                (
                    "available_on_systems",
                    models.ManyToManyField(
                        blank=True,
                        help_text="A specific list of systems where this tool is available.",
                        related_name="tool_definitions",
                        to="systems.system",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="definitions.tooldefinition",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="definitions.tooldefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ToolInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("installing", "Installing"),
                            ("installed", "installed"),
                            ("uninstalling", "Uninstalling"),
                            ("error", "Error"),
                        ],
                        default="installing",
                        max_length=20,
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        help_text="The installation path on the remote system.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "max_parallel_instances",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of parallel instances allowed for this tool installation.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(64),
                        ],
                    ),
                ),
                (
                    "agent_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific agent instance this installation is dedicated to. Null for shared tools.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_installations",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="definitions.toolinstallation",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="definitions.toolinstallation",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_installations",
                        to="systems.system",
                    ),
                ),
                (
                    "tool_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="definitions.tooldefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("tool_definition", "system", "agent_instance")},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ToolInstallationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("error", "Error")],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="definitions.toolinstallationlog",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="definitions.toolinstallationlog",
                    ),
                ),
                (
                    "tool_installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="definitions.toolinstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
