# Generated by Django 5.2.1 on 2025-10-06 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("definitions", "0001_initial"),
        ("instances", "0001_initial"),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolinstallation",
            name="mcp_server",
            field=models.OneToOneField(
                blank=True,
                help_text="The ToolInstance that this ToolInstallation manages the connection for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installation",
                to="instances.toolinstance",
            ),
        ),
        migrations.AddField(
            model_name="toolinstallation",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_installations",
                to="systems.system",
            ),
        ),
        migrations.AddField(
            model_name="toolinstallation",
            name="tool_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="definitions.tooldefinition",
            ),
        ),
        migrations.AddField(
            model_name="toolinstallationlog",
            name="tool_installation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="definitions.toolinstallation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="toolinstallation",
            unique_together={("tool_definition", "system", "agent_instance")},
        ),
    ]
