# Generated by Django 5.2.1 on 2025-10-06 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tooldefinition",
            name="raw_data",
            field=models.TextField(default="", max_length=104857600),
        ),
        migrations.AddField(
            model_name="toolinstallation",
            name="raw_data",
            field=models.TextField(default="", max_length=104857600),
        ),
        migrations.AddField(
            model_name="toolinstallationlog",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="toolinstallationlog",
            name="raw_data",
            field=models.TextField(default="", max_length=104857600),
        ),
        migrations.AddField(
            model_name="toolinstallationlog",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
