# Generated by Django 5.2.7 on 2025-10-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0003_tooldefinition_fork_of_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooldefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="toolinstallation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="toolinstallationlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
