# Generated by Django 5.2.7 on 2025-10-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "definitions",
            "0004_alter_tooldefinition_id_alter_toolinstallation_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="toolinstallation",
            name="raw_mcp_data",
            field=models.JSONField(
                blank=True,
                help_text="Cached raw MCP data including manifest, prompts, and resources.",
                null=True,
            ),
        ),
    ]
