# Generated by Django 5.2.7 on 2025-10-14 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0005_toolinstallation_raw_mcp_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tooldefinition",
            name="manifest",
        ),
        migrations.RemoveField(
            model_name="toolinstallation",
            name="raw_mcp_data",
        ),
    ]
