# Generated by Django 5.2.7 on 2025-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0006_remove_tooldefinition_manifest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooldefinition",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="toolinstallation",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="toolinstallationlog",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
