# Generated by Django 5.2.7 on 2025-10-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0007_alter_tooldefinition_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooldefinition",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="definitions.tooldefinition",
            ),
        ),
        migrations.AlterField(
            model_name="toolinstallation",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="definitions.toolinstallation",
            ),
        ),
        migrations.AlterField(
            model_name="toolinstallationlog",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="definitions.toolinstallationlog",
            ),
        ),
    ]
