# Generated by Django 5.2.1 on 2025-10-06 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildin_memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
