# Generated by Django 5.2.7 on 2025-12-03 06:30

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=64000),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="unique name of eventhandler", max_length=512
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="", help_text="description", max_length=100000
                    ),
                ),
                ("enabled", models.BooleanField(default=True, help_text="enabled")),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=True, help_text="block until finished, otherwise detach"
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        default="",
                        help_text="path of sourcecode to load function from",
                        max_length=4000,
                    ),
                ),
                (
                    "source_string",
                    models.CharField(
                        default="",
                        help_text="sourcecode string to load function from",
                        max_length=100000,
                    ),
                ),
                (
                    "source_function_name",
                    models.CharField(
                        default="",
                        help_text="full name of function to load/call",
                        max_length=4000,
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="events.eventhandler",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="events.eventhandler",
                    ),
                ),
                (
                    "receiver_agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_handlers",
                        to="agents.agent",
                    ),
                ),
                (
                    "receiver_agentInstance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_handlers",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_handlers",
                        to="events.eventtype",
                    ),
                ),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "description",
                    models.CharField(
                        default="", help_text="description", max_length=100000
                    ),
                ),
                (
                    "ignore_error",
                    models.BooleanField(
                        default=False,
                        help_text="ignore exceptions and errors at runtime",
                    ),
                ),
                (
                    "emitter_agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_subscriptions",
                        to="agents.agent",
                    ),
                ),
                (
                    "emitter_agentInstance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_subscriptions",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "eventHandler",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_subscriptions",
                        to="events.eventhandler",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="events.eventsubscription",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="events.eventsubscription",
                    ),
                ),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending execution"),
                            ("ACTIVE", "active"),
                            ("FAILED", "failed"),
                            ("SUCCESS", "success"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_events",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_events",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "agentInstanceTask",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.agentinstancetask",
                    ),
                ),
                (
                    "conversationMessage",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="events.eventexecution",
                    ),
                ),
                (
                    "llmQuery",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.llmquery",
                    ),
                ),
                (
                    "llmResponse",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.llmresponse",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="events.eventexecution",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="calls.toolcall",
                    ),
                ),
                (
                    "eventHandler",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="events.eventhandler",
                    ),
                ),
                (
                    "eventSubscription",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="events.eventsubscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="eventsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("emitter_agentInstance__isnull", True),
                        ("emitter_agent__isnull", False),
                    ),
                    models.Q(
                        ("emitter_agentInstance__isnull", False),
                        ("emitter_agent__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ensure_one_parent_is_set_for_EventSubscription",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventsubscription",
            unique_together={
                ("emitter_agent", "emitter_agentInstance", "eventHandler")
            },
        ),
        migrations.AddConstraint(
            model_name="eventhandler",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("receiver_agentInstance__isnull", True),
                        ("receiver_agent__isnull", False),
                    ),
                    models.Q(
                        ("receiver_agentInstance__isnull", False),
                        ("receiver_agent__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ensure_one_parent_is_set_for_EventHandler",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventhandler",
            unique_together={
                ("receiver_agent", "receiver_agentInstance", "event", "name")
            },
        ),
    ]
