# Generated by Django 5.2.7 on 2025-12-03 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventexecution",
            old_name="agentInstanceTask",
            new_name="agentTask",
        ),
    ]
