# Generated by Django 5.2.7 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_agentinstancetask_eventexecution_agenttask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventhandler",
            name="is_blocking",
        ),
        migrations.AddField(
            model_name="eventsubscription",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("BLOCKING", "Block until event is finished (default)"),
                    ("PARALLEL", "Run in parallel with other EventSubscriptions"),
                    ("DETACHED", "Run in background, not blocking"),
                ],
                default="BLOCKING",
                max_length=32,
            ),
        ),
    ]
