# Generated by Django 5.2.7 on 2025-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_eventhandler_is_blocking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhandler",
            name="description",
            field=models.CharField(
                blank=True, default="", help_text="description", max_length=100000
            ),
        ),
        migrations.AlterField(
            model_name="eventsubscription",
            name="description",
            field=models.CharField(
                blank=True, default="", help_text="description", max_length=100000
            ),
        ),
    ]
