# Generated by Django 5.2.7 on 2025-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_eventhandler_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhandler",
            name="source_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="path of sourcecode to load function from",
                max_length=4000,
            ),
        ),
        migrations.AlterField(
            model_name="eventhandler",
            name="source_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sourcecode string to load function from",
                max_length=100000,
            ),
        ),
    ]
