# Generated by Django 5.2.7 on 2025-12-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_alter_agentinstance_status_alter_agenttask_status"),
        ("events", "0005_alter_eventhandler_source_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubscription",
            name="reveiver_agentInstance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reveived_event_subscriptions",
                to="agents.agentinstance",
            ),
        ),
        migrations.AlterField(
            model_name="eventsubscription",
            name="emitter_agentInstance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emitted_event_subscriptions",
                to="agents.agentinstance",
            ),
        ),
    ]
