# Generated by Django 5.2.7 on 2025-12-04 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_eventsubscription_reveiver_agentinstance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventsubscription",
            old_name="reveiver_agentInstance",
            new_name="receiver_agentInstance",
        ),
    ]
