# Generated by Django 5.2.7 on 2025-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_alter_querymessagepart_content_type"),
        (
            "events",
            "0007_rename_reveiver_agentinstance_eventsubscription_receiver_agentinstance",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventexecution",
            name="agentChildTasks",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="related_parent_events",
                to="agents.agenttask",
            ),
        ),
    ]
