# Generated by Django 5.2.7 on 2025-12-03 06:30

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentInstance",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("instance_pk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "description_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A description of this specific agent instance.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("IDLE_AUTOMATED", "Idle (Automated)"),
                            ("THINKING", "Thinking"),
                            ("EXECUTING_TOOLS", "Executing Tools"),
                            ("AWAITING_USER_INPUT", "Awaiting User Input"),
                            ("AWAITING_AGENT_MESSAGE", "Awaiting Agent Message"),
                            ("AWAITING_RATE_LIMIT", "Awaiting Rate Limit"),
                            ("AWAITING_USER_CONFIRM", "Awaiting user confirmation"),
                            ("QUEUED", "Queued"),
                            ("ERROR", "Error"),
                            ("SYSTEM_OFFLINE", "System Offline"),
                        ],
                        default="IDLE",
                        max_length=30,
                    ),
                ),
                ("workingdir", models.CharField(default="", max_length=1024)),
                ("require_user_interaction", models.BooleanField(default=False)),
                (
                    "limit_max_conversation_messages",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Override the agent's default maximum number of messages in conversation history send in llm requests.",
                        null=True,
                    ),
                ),
                (
                    "limit_max_new_conversation_messages",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Override the agent's default maximum number of new messages in conversation history send in llm requests.",
                        null=True,
                    ),
                ),
                (
                    "limit_max_memory_items",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Override the agent's default maximum number of items in memory.",
                        null=True,
                    ),
                ),
                (
                    "limit_max_automated_steps",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Override the agent's default maximum number of automated steps.",
                        null=True,
                    ),
                ),
                ("automated_step_count", models.IntegerField(default=0)),
                (
                    "workingdir_write_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Allow write operations within the working directory.",
                    ),
                ),
                (
                    "access_rules",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fine-grained access rules, one per line. E.g., '!path/to/deny', '>path/to/allow', '</path/to/readonly'.",
                    ),
                ),
                (
                    "max_requests_per_minute",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Maximum requests per minute for this instance or its subtree. Null means inheriting from parent.",
                        null=True,
                    ),
                ),
                (
                    "max_token_per_minute",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Maximum tokens per minute for this instance or its subtree. Null means inheriting from parent.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AgentInstanceFork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AgentInstanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACTIVE", "ACTIVE"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("arguments", models.JSONField(default=list)),
                ("result", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("role", models.CharField(max_length=32)),
                ("hide_from_context", models.BooleanField(default=False)),
                ("pin_to_context", models.BooleanField(default=False)),
                ("trigger_query", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConversationMessagePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("tokens", models.IntegerField(default=0)),
                ("index", models.IntegerField(default=0)),
                ("content", models.CharField(max_length=1000000)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                        default="TEXT",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DebugLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("event", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoryLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_name",
                    models.CharField(
                        default="default",
                        help_text="Name of tool or other group this limit belongs to",
                        max_length=255,
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        help_text="The unique name of the rule template to override (e.g., 'fs_by_path').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of why this override exists.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lower numbers run first (not currently used, for future extension).",
                    ),
                ),
                (
                    "limit_success",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for successful calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "limit_failed",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for failed calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "limit_pending",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for pending calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "limit_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for total calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "group_name", "rule_name"],
            },
        ),
        migrations.CreateModel(
            name="LLMQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("SUCCESS", "successfull"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
                (
                    "tags_token_usage",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("tokens", models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LLMResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("completion_tokens", models.IntegerField(default=0)),
                ("prompt_tokens", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("SUCCESS", "Successfull"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QueryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("role", models.CharField(max_length=32)),
                (
                    "tags_token_usage",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("tokens", models.IntegerField(blank=True, default=None, null=True)),
                ("index", models.IntegerField(default=0)),
                (
                    "content_prefix",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "content_postfix",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QueryMessagePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("tokens", models.IntegerField(blank=True, default=None, null=True)),
                ("index", models.IntegerField(default=0)),
                (
                    "content",
                    models.CharField(
                        blank=True, default=None, max_length=1000000, null=True
                    ),
                ),
                (
                    "content_prefix",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "content_postfix",
                    models.CharField(
                        blank=True, default=None, max_length=10000, null=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                        default="TEXT",
                        max_length=255,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags used",
                        null=True,
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="the data field that we use to render the prompt, if existing",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SubAgentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("agent_pk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "limit_max_conversation_messages",
                    models.IntegerField(
                        blank=True,
                        default=20,
                        help_text="Default maximum number of messages in an agent's conversation history.",
                        null=True,
                    ),
                ),
                (
                    "limit_max_new_conversation_messages",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Default maximum number of new messages in conversation history send in llm requests. If larger than limit_max_conversation_messages messages can be skipped",
                        null=True,
                    ),
                ),
                (
                    "limit_max_memory_items",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Default maximum number of items in an agent's memory.",
                        null=True,
                    ),
                ),
                (
                    "limit_max_automated_steps",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Default maximum number of automated steps an agent can take.",
                        null=True,
                    ),
                ),
                (
                    "tool_call_syntax",
                    models.CharField(
                        choices=[
                            ("custom", "Custom (@@@tool_call(...)@@@)"),
                            ("default", "Default (LLM API Standard)"),
                        ],
                        default="default",
                        help_text="The syntax style for tool calls in the agent's output.",
                        max_length=10,
                    ),
                ),
                ("task_arguments_schema", models.JSONField(default=list)),
                ("task_result_schema", models.JSONField(default=dict)),
                (
                    "aimodel",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="providers.aimodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
