# Generated by Django 5.2.1 on 2025-10-06 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("definitions", "0001_initial"),
        ("providers", "0001_initial"),
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="available_tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents_using_this_tool",
                to="definitions.tooldefinition",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="owners",
            field=models.ManyToManyField(
                blank=True, related_name="owned_agents", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="model",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_instances",
                to="providers.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="system",
            field=models.ForeignKey(
                blank=True,
                help_text="The system this instance is assigned to run on.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_instances",
                to="systems.system",
            ),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="agent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversationMessages",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversationMessages",
                to="agents.agentinstance",
            ),
        ),
        migrations.AddField(
            model_name="debuglogentry",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debugLogEntries",
                to="agents.agentinstance",
            ),
        ),
        migrations.AddField(
            model_name="historylimit",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_limiting_rules",
                to="agents.agentinstance",
            ),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmqueries",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmqueries",
                to="agents.agentinstance",
            ),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="apikey",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llmqueries",
                to="providers.apikey",
            ),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmqueries",
                to="providers.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmResponses",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmResponses",
                to="agents.agentinstance",
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="llmQuery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmResponses",
                to="agents.llmquery",
            ),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="llmResponse",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversationMessages",
                to="agents.llmresponse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="historylimit",
            unique_together={("agentInstance", "group_name", "rule_name")},
        ),
    ]
