# Generated by Django 5.2.1 on 2025-10-06 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
