# Generated by Django 5.2.7 on 2025-12-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_initial"),
        ("events", "0002_rename_agentinstancetask_eventexecution_agenttask"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AgentInstanceTask",
            new_name="AgentTask",
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("IDLE_AUTOMATED", "Idle (Automated)"),
                    ("PROCESSING_MESSAGE", "Processing Message"),
                    ("QUERY_CREATE", "QUERY_CREATE"),
                    ("QUERY_WAITING", "QUERY_WAITING"),
                    ("QUERY_ACTIVE", "QUERY_ACTIVE"),
                    ("RESPONSE_PARSE", "RESPONSE_PARSE"),
                    ("RESPONSE_TOOLCALLS", "RESPONSE_TOOLCALLS"),
                    ("AWAITING_CONFIRMATION", "AWAITING_CONFIRMATION"),
                    ("THINKING", "Thinking"),
                    ("EXECUTING_TOOLS", "Executing Tools"),
                    ("AWAITING_USER_INPUT", "Awaiting User Input"),
                    ("AWAITING_AGENT_MESSAGE", "Awaiting Agent Message"),
                    ("AWAITING_RATE_LIMIT", "Awaiting Rate Limit"),
                    ("AWAITING_USER_CONFIRM", "Awaiting user confirmation"),
                    ("QUEUED", "Queued"),
                    ("ERROR", "Error"),
                    ("SYSTEM_OFFLINE", "System Offline"),
                ],
                default="IDLE",
                max_length=30,
            ),
        ),
    ]
