# Generated by Django 5.2.7 on 2025-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_initial"),
        ("definitions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmquery",
            old_name="model",
            new_name="aimodel",
        ),
        migrations.AlterField(
            model_name="agent",
            name="available_tools",
            field=models.ManyToManyField(
                blank=True, related_name="agents", to="definitions.tooldefinition"
            ),
        ),
    ]
