# Generated by Django 5.2.1 on 2025-10-06 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_alter_agent_created_at_alter_agent_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentinstance",
            old_name="model",
            new_name="aimodel",
        ),
    ]
