# Generated by Django 5.2.7 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_rename_agentinstancetask_agenttask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("IDLE_AUTOMATED", "Idle (Automated)"),
                    ("PROCESSING_MESSAGE", "Processing Message"),
                    ("QUERY_CREATE", "QUERY_CREATE"),
                    ("QUERY_PENDING", "QUERY_PENDING"),
                    ("QUERY_COMPILE", "QUERY_COMPILE"),
                    ("QUERY_ACTIVE", "QUERY_ACTIVE"),
                    ("RESPONSE_PARSE", "RESPONSE_PARSE"),
                    ("TOOLCALLS_PENDING", "TOOLCALLS_PENDING"),
                    ("AWAITING_CONFIRMATION", "AWAITING_CONFIRMATION"),
                    ("THINKING", "Thinking"),
                    ("EXECUTING_TOOLS", "Executing Tools"),
                    ("AWAITING_USER_INPUT", "Awaiting User Input"),
                    ("AWAITING_AGENT_MESSAGE", "Awaiting Agent Message"),
                    ("AWAITING_RATE_LIMIT", "Awaiting Rate Limit"),
                    ("AWAITING_USER_CONFIRM", "Awaiting user confirmation"),
                    ("QUEUED", "Queued"),
                    ("ERROR", "Error"),
                    ("SYSTEM_OFFLINE", "System Offline"),
                ],
                default="IDLE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="agenttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACTIVE", "ACTIVE"),
                    ("SUCCESS", "SUCCESS"),
                    ("ERROR", "ERROR"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
