# Generated by Django 5.2.7 on 2025-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_rename_model_llmquery_aimodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="agent",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
