# Generated by Django 5.2.7 on 2025-10-09 08:54

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_alter_agent_created_at_alter_agent_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentFork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                (
                    "child_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fork_origin",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "parent_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forks_created",
                        to="agents.agentinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
