# Generated by Django 5.2.7 on 2025-12-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_alter_agentinstance_status_alter_agenttask_status"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstance",
            name="aimodel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_instances",
                to="providers.aimodel",
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("IDLE_AUTOMATED", "Idle (Automated)"),
                    ("PROCESSING_MESSAGE", "Processing Message"),
                    ("QUERY_CREATE", "QUERY_CREATE"),
                    ("QUERY_PENDING", "QUERY_PENDING"),
                    ("QUERY_COMPILE", "QUERY_COMPILE"),
                    ("QUERY_ACTIVE", "QUERY_ACTIVE"),
                    ("RESPONSE_PARSE", "RESPONSE_PARSE"),
                    ("TOOLCALLS_PENDING", "TOOLCALLS_PENDING"),
                    ("TOOLCALLS_ACTIVE", "TOOLCALLS_ACTIVE"),
                    ("AWAITING_USER_INPUT", "Awaiting User Input"),
                    (
                        "AWAITING_CONFIRMATION",
                        "Awaiting User Input/Empty message by human operator to confirm continued automatic operation",
                    ),
                    ("ERROR", "Error"),
                    ("SYSTEM_OFFLINE", "System Offline"),
                ],
                default="IDLE",
                max_length=30,
            ),
        ),
    ]
