# Generated by Django 5.2.7 on 2025-10-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentfork'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentfork',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.agentfork'),
        ),
        migrations.AddField(
            model_name='agentfork',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.agentfork'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.agentinstance'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.agentinstance'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.conversationmessage'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.conversationmessage'),
        ),
        migrations.AddField(
            model_name='debuglogentry',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.debuglogentry'),
        ),
        migrations.AddField(
            model_name='debuglogentry',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.debuglogentry'),
        ),
        migrations.AddField(
            model_name='llmquery',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.llmquery'),
        ),
        migrations.AddField(
            model_name='llmquery',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.llmquery'),
        ),
        migrations.AddField(
            model_name='llmresponse',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='agents.llmresponse'),
        ),
        migrations.AddField(
            model_name='llmresponse',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='agents.llmresponse'),
        ),
    ]
