# Generated by Django 5.2.7 on 2025-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_alter_agentinstance_aimodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="task_arguments_schema",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="agent",
            name="task_result_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("PROCESSING_MESSAGE", "Processing Message"),
                    ("QUERY_CREATE", "QUERY_CREATE"),
                    ("QUERY_PENDING", "QUERY_PENDING"),
                    ("QUERY_COMPILE", "QUERY_COMPILE"),
                    ("QUERY_ACTIVE", "QUERY_ACTIVE"),
                    ("RESPONSE_PROCESS", "RESPONSE_PROCESS"),
                    ("TOOLCALLS_PENDING", "TOOLCALLS_PENDING"),
                    ("TOOLCALLS_ACTIVE", "TOOLCALLS_ACTIVE"),
                    ("AWAITING_USER_INPUT", "Awaiting User Input"),
                    ("ERROR", "Error"),
                    ("SYSTEM_OFFLINE", "System Offline"),
                ],
                default="IDLE",
                max_length=30,
            ),
        ),
    ]
