# Generated by Django 5.2.7 on 2025-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_alter_agent_task_arguments_schema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="group",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
    ]
