# Generated by Django 5.2.7 on 2025-10-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_agent_fork_of_agent_raw_data_reference_and_more"),
        ("providers", "0003_aimodel_fork_of_aimodel_raw_data_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmquery",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmQueries",
                to="agents.agent",
            ),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmQueries",
                to="agents.agentinstance",
            ),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="aimodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmQueries",
                to="providers.aimodel",
            ),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="apikey",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llmQueries",
                to="providers.apikey",
            ),
        ),
    ]
