# Generated by Django 5.2.7 on 2025-12-14 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_agenttask_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="children",
                to="agents.agenttask",
            ),
        ),
    ]
