# Generated by Django 5.2.7 on 2025-10-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_alter_agentinstance_status_alter_llmquery_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("SUCCESS", "Successfull"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
