# Generated by Django 5.2.7 on 2025-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_agenttask_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querymessagepart",
            name="content_type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image"), ("FILE", "File")],
                default="TEXT",
                max_length=255,
            ),
        ),
    ]
