# Generated by Django 5.2.9 on 2025-12-18 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_alter_querymessagepart_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="tool_call_syntax",
        ),
        migrations.DeleteModel(
            name="QueryQueue",
        ),
    ]
