# Generated by Django 5.2.7 on 2025-10-14 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_alter_llmresponse_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmresponse",
            name="llmQuery",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="llmResponses",
                to="agents.llmquery",
            ),
        ),
    ]
