# Generated by Django 5.2.7 on 2025-10-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0010_alter_llmresponse_llmquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessage",
            name="llmResponse",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="conversationMessages",
                to="agents.llmresponse",
            ),
        ),
    ]
