# Generated by Django 5.2.7 on 2025-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_alter_conversationmessage_llmresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="limit_max_automated_steps",
            field=models.IntegerField(
                blank=True,
                default=25,
                help_text="Default maximum number of automated steps an agent can take.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="limit_max_conversation_messages",
            field=models.IntegerField(
                blank=True,
                default=100,
                help_text="Default maximum number of messages in an agent's conversation history.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="limit_max_memory_items",
            field=models.IntegerField(
                blank=True,
                default=100,
                help_text="Default maximum number of items in an agent's memory.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="limit_max_automated_steps",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Override the agent's default maximum number of automated steps.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="limit_max_conversation_messages",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Override the agent's default maximum number of messages in conversation history.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="limit_max_memory_items",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Override the agent's default maximum number of items in memory.",
                null=True,
            ),
        ),
    ]
