# Generated by Django 5.2.7 on 2025-10-15 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0012_agent_limit_max_automated_steps_and_more"),
        ("providers", "0008_alter_aimodel_raw_data_alter_apikey_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="aimodel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to="providers.aimodel",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="limit_max_automated_steps",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Default maximum number of automated steps an agent can take.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="limit_max_conversation_messages",
            field=models.IntegerField(
                blank=True,
                default=20,
                help_text="Default maximum number of messages in an agent's conversation history.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="limit_max_memory_items",
            field=models.IntegerField(
                blank=True,
                default=10,
                help_text="Default maximum number of items in an agent's memory.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="agentfork",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
