# Generated by Django 5.2.7 on 2025-10-15 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0013_alter_agent_aimodel_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="historylimit",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="historylimit",
            name="agentInstance",
        ),
    ]
