# Generated by Django 5.2.7 on 2025-10-15 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0014_alter_historylimit_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historylimit",
            name="agent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_limiting_rules",
                to="agents.agent",
            ),
        ),
    ]
