# Generated by Django 5.2.7 on 2025-10-15 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0017_alter_agentinstancefork_child_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstancefork",
            name="parent_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks_created",
                to="agents.agentinstance",
            ),
        ),
    ]
