# Generated by Django 5.2.7 on 2025-10-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0018_alter_agentinstancefork_parent_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.agentinstance",
            ),
        ),
        migrations.AlterField(
            model_name="agentinstancefork",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.agentinstancefork",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.conversationmessage",
            ),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.debuglogentry",
            ),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.llmquery",
            ),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="agents.llmresponse",
            ),
        ),
    ]
