# Generated by Django 5.2.7 on 2025-10-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0022_subagentlink"),
        ("calls", "0007_alter_toolcall_fork_of_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessagepart",
            name="toolCall",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="conversationMessagePart",
                to="calls.toolcall",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessagepart",
            name="toolResponse",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="conversationMessagePart",
                to="calls.toolresponse",
            ),
        ),
    ]
