# Generated by Django 5.2.7 on 2025-10-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0023_alter_conversationmessagepart_toolcall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinstance",
            name="max_requests_per_minute",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Maximum requests per minute for this instance or its subtree. Null means inheriting from parent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="max_token_per_minute",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Maximum tokens per minute for this instance or its subtree. Null means inheriting from parent.",
                null=True,
            ),
        ),
    ]
