# Generated by Django 5.2.7 on 2025-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0024_agentinstance_max_requests_per_minute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("IDLE_AUTOMATED", "Idle (Automated)"),
                    ("THINKING", "Thinking"),
                    ("EXECUTING_TOOLS", "Executing Tools"),
                    ("AWAITING_USER_INPUT", "Awaiting User Input"),
                    ("AWAITING_AGENT_MESSAGE", "Awaiting Agent Message"),
                    ("AWAITING_RATE_LIMIT", "Awaiting Rate Limit"),
                    ("FINISHED", "Finished"),
                    ("ERROR", "Error"),
                    ("SYSTEM_OFFLINE", "System Offline"),
                ],
                default="IDLE",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="SubAgentLink",
        ),
    ]
