# Generated by Django 5.2.7 on 2025-10-23 00:39

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0026_subagentlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("IDLE_AUTOMATED", "Idle (Automated)"),
                    ("THINKING", "Thinking"),
                    ("EXECUTING_TOOLS", "Executing Tools"),
                    ("AWAITING_USER_INPUT", "Awaiting User Input"),
                    ("AWAITING_AGENT_MESSAGE", "Awaiting Agent Message"),
                    ("AWAITING_RATE_LIMIT", "Awaiting Rate Limit"),
                    ("QUEUED", "Queued"),
                    ("FINISHED", "Finished"),
                    ("ERROR", "Error"),
                    ("SYSTEM_OFFLINE", "System Offline"),
                ],
                default="IDLE",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="QueryQueue",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "agent_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="queue_entry",
                        serialize=False,
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.queryqueue",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.queryqueue",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
