# Generated by Django 5.2.7 on 2025-10-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0028_alter_agentinstance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessagepart",
            name="content",
            field=models.CharField(max_length=1000000),
        ),
    ]
