# Generated by Django 5.2.7 on 2025-10-31 22:29

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0029_alter_conversationmessagepart_content"),
        ("builtin_filesystem", "0007_alter_fslogentry_fork_of_and_more"),
        ("calls", "0007_alter_toolcall_fork_of_and_more"),
        ("core", "0014_alter_prompt_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmessagepart",
            name="promptVariant",
        ),
        migrations.RemoveField(
            model_name="conversationmessagepart",
            name="toolResponse",
        ),
        migrations.AddField(
            model_name="conversationmessagepart",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="tags_token_usage",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="conversationmessagepart",
            name="conversationMessage",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="conversationMessageParts",
                to="agents.conversationmessage",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessagepart",
            name="toolCall",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="conversationMessageParts",
                to="calls.toolcall",
            ),
        ),
        migrations.CreateModel(
            name="QueryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("role", models.CharField(max_length=32)),
                (
                    "tags_token_usage",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("tokens", models.IntegerField(default=0)),
                ("index", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queryMessages",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queryMessages",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.querymessage",
                    ),
                ),
                (
                    "llmQuery",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="queryMessages",
                        to="agents.llmquery",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.querymessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QueryMessagePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("tokens", models.IntegerField(default=0)),
                ("index", models.IntegerField(default=0)),
                ("content", models.CharField(max_length=1000000)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags used",
                        null=True,
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="the data field that we use to render the prompt, if existing",
                        null=True,
                    ),
                ),
                (
                    "conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="used_in_queryMessageParts",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "conversationMessagePart",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="used_in_queryMessageParts",
                        to="agents.conversationmessagepart",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.querymessagepart",
                    ),
                ),
                (
                    "fsLogEntry",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="used_in_queryMessageParts",
                        to="builtin_filesystem.fslogentry",
                    ),
                ),
                (
                    "promptVariant",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="queryMessageParts",
                        to="core.promptvariant",
                    ),
                ),
                (
                    "queryMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="parts",
                        to="agents.querymessage",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.querymessagepart",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="queryMessageParts",
                        to="calls.toolcall",
                    ),
                ),
                (
                    "toolResponse",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="queryMessageParts",
                        to="calls.toolresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
