# Generated by Django 5.2.7 on 2025-10-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0030_remove_conversationmessagepart_promptvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="querymessage",
            name="content_postfix",
            field=models.CharField(
                blank=True, default=None, max_length=10000, null=True
            ),
        ),
        migrations.AddField(
            model_name="querymessage",
            name="content_prefix",
            field=models.CharField(
                blank=True, default=None, max_length=10000, null=True
            ),
        ),
        migrations.AddField(
            model_name="querymessagepart",
            name="content_postfix",
            field=models.CharField(
                blank=True, default=None, max_length=10000, null=True
            ),
        ),
        migrations.AddField(
            model_name="querymessagepart",
            name="content_prefix",
            field=models.CharField(
                blank=True, default=None, max_length=10000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="querymessagepart",
            name="content",
            field=models.CharField(
                blank=True, default=None, max_length=1000000, null=True
            ),
        ),
    ]
