# Generated by Django 5.2.7 on 2025-11-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0031_querymessage_content_postfix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querymessagepart",
            name="queryMessage",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="queryMessageParts",
                to="agents.querymessage",
            ),
        ),
    ]
