# Generated by Django 5.2.7 on 2025-11-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0032_alter_querymessagepart_querymessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querymessagepart",
            name="tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
