# Generated by Django 5.2.7 on 2025-11-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0033_alter_querymessagepart_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmquery",
            name="tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="querymessage",
            name="tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
