# Generated by Django 5.2.7 on 2025-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0034_alter_llmquery_tokens_alter_querymessage_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessagepart",
            name="content_type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                default="TEXT",
                max_length=255,
            ),
        ),
    ]
