# Generated by Django 5.2.7 on 2025-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0035_conversationmessagepart_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="querymessagepart",
            name="content_type",
            field=models.CharField(
                choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                default="TEXT",
                max_length=255,
            ),
        ),
    ]
