# Generated by Django 5.2.7 on 2025-11-03 09:44

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0036_querymessagepart_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventReceiverFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            (
                                "event_agentinstance_created",
                                "event_agentinstance_created(agent, agentInstance)",
                            ),
                            (
                                "event_conversationMessage_added",
                                "event_conversationMessage_added(agent, agentInstance, conversationMessage)",
                            ),
                            (
                                "event_llmquery_pre_execute",
                                "event_llmquery_pre_execute(agent, agentInstance, llmQuery)",
                            ),
                            (
                                "event_llmquery_successfull",
                                "event_llmquery_successfull(agent, agentInstance, llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmquery_failed",
                                "event_llmquery_failed(llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmresponse_pre_parse",
                                "event_llmresponse_pre_parse(llmQuery, llmResponse, response_string_full)",
                            ),
                            (
                                "event_llmresponse_post_parse",
                                "event_llmresponse_post_parse(llmQuery, llmResponse, response_string_full, parts)",
                            ),
                            (
                                "event_llmresponse_pre_tool_calls",
                                "event_llmresponse_pre_tool_calls(llmQuery, llmResponse, conversationMessage, toolcalls)",
                            ),
                            (
                                "event_llmresponse_pre_tool_call",
                                "event_llmresponse_pre_tool_call(llmQuery, llmResponse, conversationMessage, toolcall)",
                            ),
                            (
                                "event_llmresponse_post_tool_call",
                                "event_llmresponse_post_tool_call(llmQuery, llmResponse, conversationMessage, toolcall)",
                            ),
                            (
                                "event_llmresponse_post_tool_calls",
                                "event_llmresponse_post_tool_calls(llmQuery, llmResponse, conversationMessage, toolcalls)",
                            ),
                            (
                                "event_llmresponse_finished",
                                "event_llmresponse_finished(llmQuery, llmResponse, conversationMessage)",
                            ),
                        ],
                        default="event_agentinstance_created",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", help_text="source", max_length=10000),
                ),
                (
                    "description",
                    models.CharField(default="", help_text="source", max_length=100000),
                ),
                (
                    "source",
                    models.CharField(default="", help_text="source", max_length=100000),
                ),
                ("is_public", models.BooleanField(default=False, help_text="pubic")),
                ("enabled", models.BooleanField(default=False, help_text="enabled")),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_receiver_functions",
                        to="agents.agent",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.eventreceiverfunction",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.eventreceiverfunction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "description",
                    models.CharField(default="", help_text="source", max_length=100000),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_assignments",
                        to="agents.agent",
                    ),
                ),
                
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
