# Generated by Django 5.2.7 on 2025-11-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0037_eventreceiverfunction_eventassignment"),
    ]

    operations = [

        migrations.AddField(
            model_name="eventreceiverfunction",
            name="agentInstance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_receiver_functions",
                to="agents.agentinstance",
            ),
        ),
        migrations.AlterField(
            model_name="eventreceiverfunction",
            name="description",
            field=models.CharField(
                default="", help_text="description", max_length=100000
            ),
        ),
        migrations.AlterField(
            model_name="eventreceiverfunction",
            name="event",
            field=models.CharField(
                choices=[
                    (
                        "event_agentinstance_created",
                        "event_agentinstance_created(agent, agentInstance)",
                    ),
                    (
                        "event_conversationMessage_added",
                        "event_conversationMessage_added(agent, agentInstance, conversationMessage)",
                    ),
                    (
                        "event_llmquery_pre_create",
                        "event_llmquery_pre_create(agent, agentInstance, conversationMessage)",
                    ),
                    (
                        "event_llmquery_post_create",
                        "event_llmquery_post_create(agent, agentInstance, llmQuery)",
                    ),
                    (
                        "event_llmquery_pre_execute",
                        "event_llmquery_pre_execute(agent, agentInstance, llmQuery)",
                    ),
                    (
                        "event_llmquery_successfull",
                        "event_llmquery_successfull(agent, agentInstance, llmQuery, llmResponse, conversationMessage)",
                    ),
                    (
                        "event_llmquery_failed",
                        "event_llmquery_failed(llmQuery, llmResponse, conversationMessage)",
                    ),
                    (
                        "event_llmresponse_pre_parse",
                        "event_llmresponse_pre_parse(llmQuery, llmResponse, response_string_full)",
                    ),
                    (
                        "event_llmresponse_post_parse",
                        "event_llmresponse_post_parse(llmQuery, llmResponse, response_string_full, parts)",
                    ),
                    (
                        "event_llmresponse_pre_tool_calls",
                        "event_llmresponse_pre_tool_calls(llmQuery, llmResponse, conversationMessage, toolcalls)",
                    ),
                    (
                        "event_llmresponse_pre_tool_call",
                        "event_llmresponse_pre_tool_call(llmQuery, llmResponse, conversationMessage, toolcall)",
                    ),
                    (
                        "event_llmresponse_post_tool_call",
                        "event_llmresponse_post_tool_call(llmQuery, llmResponse, conversationMessage, toolcall)",
                    ),
                    (
                        "event_llmresponse_post_tool_calls",
                        "event_llmresponse_post_tool_calls(llmQuery, llmResponse, conversationMessage, toolcalls)",
                    ),
                    (
                        "event_llmresponse_finished",
                        "event_llmresponse_finished(llmQuery, llmResponse, conversationMessage)",
                    ),
                ],
                default="event_agentinstance_created",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="eventreceiverfunction",
            name="name",
            field=models.CharField(default="", help_text="name", max_length=10000),
        ),
        migrations.AlterField(
            model_name="eventreceiverfunction",
            name="source",
            field=models.CharField(
                default="", help_text="sourcecode", max_length=100000
            ),
        ),
    ]
