# Generated by Django 5.2.7 on 2025-11-05 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0040_agent_limit_max_new_conversation_messages_and_more"),
    ]

    operations = [

    ]
