# Generated by Django 5.2.7 on 2025-11-05 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0041_delete_eventassignment"),
    ]

    operations = [

      


    ]
