# Generated by Django 5.2.7 on 2025-11-05 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0042_remove_eventhandler_agent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventSubscription",
        ),
    ]
