# Generated by Django 5.2.7 on 2025-11-05 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0043_delete_eventsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventhandler",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="eventhandler",
            name="agentInstance",
        ),
        migrations.RemoveField(
            model_name="eventhandler",
            name="fork_of",
        ),
        migrations.RemoveField(
            model_name="eventhandler",
            name="raw_data_reference",
        ),
        migrations.RemoveField(
            model_name="eventreceiverfunction",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="eventreceiverfunction",
            name="agentInstance",
        ),
        migrations.RemoveField(
            model_name="eventreceiverfunction",
            name="fork_of",
        ),
        migrations.RemoveField(
            model_name="eventreceiverfunction",
            name="raw_data_reference",
        ),
        migrations.DeleteModel(
            name="EventExecution",
        ),
        migrations.DeleteModel(
            name="EventHandler",
        ),
        migrations.DeleteModel(
            name="EventReceiverFunction",
        ),
    ]
