# Generated by Django 5.2.7 on 2025-11-05 08:02

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0044_remove_eventhandler_agent_and_more"),
        ("calls", "0008_toolcall_conversationmessagepart"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "eventtype",
                    models.CharField(
                        choices=[
                            (
                                "event_agentinstance_created",
                                "event_agentinstance_created(agent, agentInstance)",
                            ),
                            (
                                "event_conversationMessage_added",
                                "event_conversationMessage_added(agent, agentInstance, conversationMessage)",
                            ),
                            (
                                "event_llmquery_pre_create",
                                "event_llmquery_pre_create(agent, agentInstance)",
                            ),
                            (
                                "event_llmquery_post_create",
                                "event_llmquery_post_create(agent, agentInstance, llmQuery)",
                            ),
                            (
                                "event_llmquery_pre_execute",
                                "event_llmquery_pre_execute(agent, agentInstance, llmQuery)",
                            ),
                            (
                                "event_llmquery_successfull",
                                "event_llmquery_successfull(agent, agentInstance, llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmquery_failed",
                                "event_llmquery_failed(llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmresponse_pre_parse",
                                "event_llmresponse_pre_parse(llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmresponse_post_parse",
                                "event_llmresponse_post_parse(llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmresponse_pre_tool_calls",
                                "event_llmresponse_pre_tool_calls(llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmresponse_pre_tool_call",
                                "event_llmresponse_pre_tool_call(llmQuery, llmResponse, conversationMessage, toolcall)",
                            ),
                            (
                                "event_llmresponse_post_tool_call",
                                "event_llmresponse_post_tool_call(llmQuery, llmResponse, conversationMessage, toolcall)",
                            ),
                            (
                                "event_llmresponse_post_tool_calls",
                                "event_llmresponse_post_tool_calls(llmQuery, llmResponse, conversationMessage)",
                            ),
                            (
                                "event_llmresponse_finished",
                                "event_llmresponse_finished(llmQuery, llmResponse, conversationMessage)",
                            ),
                        ],
                        default="event_agentinstance_created",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", help_text="name", max_length=10000),
                ),
                (
                    "description",
                    models.CharField(
                        default="", help_text="description", max_length=100000
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        default="", help_text="sourcecode", max_length=100000
                    ),
                ),
                ("is_public", models.BooleanField(default=False, help_text="pubic")),
                ("enabled", models.BooleanField(default=False, help_text="enabled")),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=True, help_text="block until finished, otherwise detach"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_receiver_functions",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_receiver_functions",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.eventhandler",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.eventhandler",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "description",
                    models.CharField(default="", help_text="source", max_length=100000),
                ),
                (
                    "ignore_error",
                    models.BooleanField(
                        default=False,
                        help_text="ignore exceptions and errors at runtime",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_subscriptions",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_subscriptions",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "eventHandler",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_subscriptions",
                        to="agents.eventhandler",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.eventsubscription",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.eventsubscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending execution"),
                            ("ACTIVE", "active"),
                            ("FAILED", "failed"),
                            ("SUCCESS", "success"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                (
                    "arg_agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_events",
                        to="agents.agent",
                    ),
                ),
                (
                    "arg_agentInstance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_events",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "arg_conversationMessage",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "arg_llmQuery",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.llmquery",
                    ),
                ),
                (
                    "arg_llmResponse",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.llmresponse",
                    ),
                ),
                (
                    "arg_toolCall",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="calls.toolcall",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="agents.eventexecution",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="agents.eventexecution",
                    ),
                ),
                (
                    "eventHandler",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.eventhandler",
                    ),
                ),
                (
                    "eventSubscription",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_events",
                        to="agents.eventsubscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
