from django.db import models
from django_enum import EnumField
from server.models.base_model import BaseModel
from django.core.exceptions import ValidationError

from server.models.content import GenericContent
from server.models.enums.message_enums import MessageContentType
from server.models.queries.query_message import QueryMessage
from server.models.queries.query_message_part import QueryMessagePart

class QueryStatus(models.TextChoices):
    ACTIVE = 'ACTIVE', 'Active'
    WAITING = 'WAITING', 'Waiting (System Blocked)'
    SUCCESS = 'SUCCESS', 'Success (Terminal)'
    FAILURE = 'FAILURE', 'Failure (Terminal)'

class Query(BaseModel):
    #aimodel         = models.ForeignKey("server.AiModel"        , null=False, on_delete=models.CASCADE, related_name="related_queries")
    apikey           = models.ForeignKey("server.ApiKey"  , null=True , on_delete=models.SET_NULL,related_name="related_queries", blank=True)
    session_version  = models.ForeignKey("server.SessionVersionModel", null=False, on_delete=models.CASCADE, related_name='related_queries')
    trigger_message = models.ForeignKey("server.Message" , null=True, blank=True, on_delete=models.CASCADE, related_name='related_queries')  # this message was generated by this response

    status = EnumField(QueryStatus, default=QueryStatus.WAITING)

    tags_token_usage = models.JSONField(default=dict, null=True, blank=True)
    tokens =  models.IntegerField(default=None, blank=True, null=True)

    @property
    def response(self):
        return self.related_response # pyright: ignore[reportAttributeAccessIssue]

    def add_message(self, role:str, content:str|dict, content_template: str|None = None):
        if isinstance(content, str):
            db_content = GenericContent.from_text(content)
            db_content_type = MessageContentType.TEXT
        elif isinstance(content, dict):
            db_content = GenericContent.from_data(content)
            db_content_type = MessageContentType.TEMPLATE
        db_content_template = None
        if content_template:
            db_content_template = GenericContent.from_text(content_template)

        query_message = QueryMessage.objects.create(role=role, query=self)
        query_message_part = QueryMessagePart.objects.create(
            content = db_content,
            content_type = db_content_type,
            content_template = db_content_template,
            query_message = query_message,
        )
        return query_message, query_message_part

    def compile(self):
        messages = []
        tokens = 0
        tags_token_usages = []
        for message in self.query_messages.all().order_by("index", "-pk"):
            try:
                qm =  message.compile()
                messages.append(qm)
                tokens += message.tokens
                tags_token_usages.append(message.tags_token_usage)
            except Exception as e:
                print("Failed to compile", message)
                raise e
        tags_token_usage = self.merge_tag_usage(tags_token_usages)
        if self.tokens != tokens:
            self.tokens = tokens
            self.tags_token_usage = tags_token_usage
            self.save()
        return messages

    def merge_tag_usage(self, list_of_tag_dicts):
        def merge_into(a, b):
            for key, bval in b.items():
                if key == "tokens":
                    a["tokens"] = a.get("tokens", 0) + bval
                else:
                    if key not in a:
                        a[key] = {}
                    merge_into(a[key], bval)
            return a
        result = {}
        for d in list_of_tag_dicts:
            merge_into(result, d)
        return result

    def save(self, *args, **kwargs):
        #if self.pk:
        #    raise ValidationError(f"You may not edit an existing {self._meta.model_name}")
        super().save(*args, **kwargs) 
