[pytest]
DJANGO_SETTINGS_MODULE = config.settings

testpaths =
    agents/tests
    core/tests
    launcher/tests
    providers/tests
    systems/tests
    tools/calls/tests
    tools/definitions/tests
    tools/instances/tests
    tools/primitives/tests
    tools/builtin_a2a/tests
    tools/builtin_filesystem/tests
    tools/builtin_memory/tests
