# Generated by Django 5.2.7 on 2025-10-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptstring',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='core.promptstring'),
        ),
        migrations.AddField(
            model_name='promptstring',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='core.promptstring'),
        ),
    ]
