# Generated by Django 5.2.7 on 2025-10-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0020_alter_agent_fork_of_alter_agent_raw_data_reference_and_more"),
        ("core", "0005_alter_promptstring_fork_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptstring",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_prompts",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="promptstring",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
