# Generated by Django 5.2.7 on 2025-10-16 07:44

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0020_alter_agent_fork_of_alter_agent_raw_data_reference_and_more"),
        ("core", "0006_promptstring_agent_promptstring_is_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("source", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A description of what this prompt is for.",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="core.prompt",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="core.prompt",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "key"],
                "unique_together": {("source", "key")},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PromptVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("value", models.TextField(default="", max_length=1048576)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_variants",
                        to="agents.agent",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="core.promptvariant",
                    ),
                ),
                (
                    "next_version",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prev_version",
                        to="core.promptvariant",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_prompt_variants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.prompt",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="core.promptvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="PromptString",
        ),
    ]
