# Generated by Django 5.2.7 on 2025-10-16 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_prompt_promptvariant_delete_promptstring"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together=set(),
        ),
    ]
