# Generated by Django 5.2.7 on 2025-10-30 13:57

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0029_alter_conversationmessagepart_content"),
        ("core", "0008_alter_prompt_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPromptRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("role", models.CharField(default="user", max_length=32)),
                (
                    "insert_at",
                    models.CharField(
                        choices=[
                            ("TOP", "Top most"),
                            ("POST_TOP", "Below Top most"),
                            ("PRE_CHAT", "Right before chat messages"),
                            ("POST_CHAT", "Right after chat messages"),
                        ],
                        default="TOP",
                        max_length=30,
                    ),
                ),
                (
                    "index",
                    models.IntegerField(
                        default=0, help_text="Ordering inside the insert_at point"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_prompt_relations",
                        to="agents.agent",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="core.agentpromptrelation",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_prompt_relations",
                        to="core.prompt",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="core.agentpromptrelation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
