# Generated by Django 5.2.7 on 2025-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_agentpromptrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptvariant",
            name="version_nr",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="AgentPromptRelation",
        ),
    ]
