# Generated by Django 5.2.7 on 2025-10-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_agentpromptrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="data_lambda",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A lambda function that return the data to render",
            ),
        ),
    ]
