# Generated by Django 5.2.7 on 2025-12-03 06:30

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("name", models.CharField(max_length=512)),
                ("url", models.CharField(default="", max_length=512)),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="providers.apiprovider",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="providers.apiprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("comment", models.CharField(default="", max_length=512, null=True)),
                ("key", models.CharField(max_length=512)),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="providers.apikey",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="providers.apikey",
                    ),
                ),
                (
                    "apiProvider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apikeys",
                        to="providers.apiprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("name", models.CharField(max_length=512)),
                ("enabled", models.BooleanField(default=True)),
                ("max_prompt_tokens", models.IntegerField(default=1000000)),
                ("max_response_tokens", models.IntegerField(default=1000000)),
                ("limit_request_per_day", models.IntegerField(default=0)),
                ("limit_request_per_minute", models.IntegerField(default=0)),
                ("limit_tokens_per_day", models.IntegerField(default=0)),
                ("limit_tokens_per_minute", models.IntegerField(default=0)),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="providers.aimodel",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="providers.aimodel",
                    ),
                ),
                (
                    "apiProvider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aimodels",
                        to="providers.apiprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
