# Generated by Django 5.2.9 on 2025-12-18 01:36

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="context_length",
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="description",
            field=models.CharField(blank=True, default="", max_length=65000),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="filesize",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="is_cloud",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="AiModelFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("name", models.CharField(max_length=512)),
                ("enabled", models.BooleanField(default=True)),
                ("is_cloud", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=65000),
                ),
                (
                    "apiProvider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aimodelfamilys",
                        to="providers.apiprovider",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="providers.aimodelfamily",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="providers.aimodelfamily",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
