# Generated by Django 5.2.7 on 2025-10-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="apiProvider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aimodels",
                to="providers.apiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="apiprovider",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="apiprovider",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
