# Generated by Django 5.2.9 on 2025-12-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_aimodel_context_length_aimodel_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="vision",
            field=models.BooleanField(default=False),
        ),
    ]
