# Generated by Django 5.2.7 on 2025-10-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "providers",
            "0002_alter_aimodel_apiprovider_alter_aimodel_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="providers.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="providers.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="providers.apikey",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="providers.apikey",
            ),
        ),
        migrations.AddField(
            model_name="apiprovider",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="providers.apiprovider",
            ),
        ),
        migrations.AddField(
            model_name="apiprovider",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="providers.apiprovider",
            ),
        ),
    ]
