# Generated by Django 5.2.7 on 2025-10-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_aimodel_fork_of_aimodel_raw_data_reference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="max_tokens",
        ),
        migrations.AddField(
            model_name="aimodel",
            name="max_prompt_tokens",
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="max_response_tokens",
            field=models.IntegerField(default=1000000),
        ),
    ]
