# Generated by Django 5.2.7 on 2025-10-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "providers",
            "0004_remove_aimodel_max_tokens_aimodel_max_prompt_tokens_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="free_limit_per_day",
        ),
        migrations.AddField(
            model_name="aimodel",
            name="limit_request_per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="limit_request_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="limit_tokens_per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="limit_tokens_per_minute",
            field=models.IntegerField(default=0),
        ),
    ]
