# Generated by Django 5.2.7 on 2025-10-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0005_remove_aimodel_free_limit_per_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="comment",
            field=models.CharField(default="", max_length=512),
        ),
    ]
