# Generated by Django 5.2.7 on 2025-10-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0006_alter_apikey_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="comment",
            field=models.CharField(default="", max_length=512, null=True),
        ),
    ]
