# Generated by Django 5.2.7 on 2025-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0007_alter_apikey_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="apiprovider",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
