# Generated by Django 5.2.7 on 2025-10-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0009_alter_aimodel_fork_of_alter_apikey_fork_of_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="providers.aimodel",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="providers.aimodel",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="providers.apikey",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="providers.apikey",
            ),
        ),
        migrations.AlterField(
            model_name="apiprovider",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="providers.apiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="apiprovider",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="providers.apiprovider",
            ),
        ),
    ]
