# Generated by Django 5.2.7 on 2025-10-09 05:32

import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0002_initial"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                ("track", models.CharField(blank=True, max_length=128, null=True)),
                ("layer", models.CharField(blank=True, max_length=128, null=True)),
                ("index", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "next_version",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="prev_version",
                        to="builtin_memory.memoryitem",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="memoryItems",
                        to="calls.toolcall",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
