# Generated by Django 5.2.7 on 2025-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="created_at",
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
