# Generated by Django 5.2.7 on 2025-10-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_alter_llmquery_agent_alter_llmquery_agentinstance_and_more"),
        ("builtin_memory", "0003_memoryitem_fork_of_memoryitem_raw_data_reference"),
        ("calls", "0003_toolcall_fork_of_toolcall_raw_data_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoryItems",
                to="agents.agent",
            ),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="agentInstance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoryItems",
                to="agents.agentinstance",
            ),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="index",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="toolCall",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoryItem",
                to="calls.toolcall",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["track", "layer"], name="builtin_mem_track_bca7ae_idx"
            ),
        ),
    ]
