# Generated by Django 5.2.7 on 2025-10-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_memory", "0005_alter_memoryitem_raw_data"),
        ("calls", "0005_alter_toolcall_raw_data_alter_toolresponse_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="next_version",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="prev_version",
                to="builtin_memory.memoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="toolCall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoryItem",
                to="calls.toolcall",
            ),
        ),
    ]
