# Generated by Django 5.2.7 on 2025-10-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_memory", "0008_alter_memoryitem_fork_of_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="next_version",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="prev_version",
                to="builtin_memory.memoryitem",
            ),
        ),
    ]
