# Generated by Django 5.2.9 on 2026-05-08 04:42

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FsLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("is_newest_version", models.BooleanField(db_index=True, default=True)),
                ("path", models.CharField(max_length=512)),
                ("filter", models.CharField(default=None, max_length=4096, null=True)),
                ("recursive", models.BooleanField(default=False)),
                (
                    "load_mode",
                    models.CharField(
                        db_index=True, default=None, max_length=16, null=True
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_directory", models.BooleanField(default=False)),
                ("exists_on_fs", models.BooleanField(default=False)),
                ("fs_created", models.DateTimeField(default=None, null=True)),
                ("fs_modified", models.DateTimeField(default=None, null=True)),
                ("fs_lastread", models.DateTimeField(default=None, null=True)),
                ("fs_size", models.IntegerField(default=0)),
                ("action", models.CharField(max_length=16)),
                ("content_diff", models.TextField(default="", max_length=10485760)),
                ("stored_as", models.CharField(max_length=16)),
                (
                    "summary",
                    models.TextField(
                        blank=True, default=None, max_length=5242880, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
