# Generated by Django 5.2.9 on 2026-05-08 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fslogentry",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="server.agentmodel",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="agent_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="server.instancemodel",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="conversationMessage",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="server.conversationmessage",
            ),
        ),
       
        
    ]
