# Generated by Django 5.2.1 on 2025-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatestring",
            name="source",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="templatestring",
            name="key",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="templatestring",
            name="value",
            field=models.TextField(default=b"", max_length=1048576),
        ),
    ]
