# Generated by Django 5.2.1 on 2025-09-25 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_promptstring_delete_templatestring"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="promptstring",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="promptstring",
            name="next_version",
            field=models.OneToOneField(
                blank=True,
                help_text="Points to the next version in the prompt's history. Null for the latest version.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_version_of",
                to="common.promptstring",
            ),
        ),
    ]
