# Generated by Django 5.2.1 on 2025-09-26 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_promptstring_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptstring",
            name="next_version",
            field=models.OneToOneField(
                blank=True,
                help_text="Points to the next version in the prompt's history. Null for the latest version.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prev_version",
                to="common.promptstring",
            ),
        ),
    ]
