# Generated by Django 5.2.1 on 2025-09-20 18:20

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent", "0001_initial"),
        ("tools_common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("track", models.CharField(blank=True, max_length=128, null=True)),
                ("layer", models.CharField(blank=True, max_length=128, null=True)),
                ("index", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="agent.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="agent.conversationmessage",
                    ),
                ),
                (
                    "next_version",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prev_version",
                        to="tools_memory.memoryitem",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoryItems",
                        to="tools_common.toolcall",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
