# Generated by Django 5.2.1 on 2025-09-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_common", "0001_initial"),
        ("tools_memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="toolCall",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoryItems",
                to="tools_common.toolcall",
            ),
        ),
    ]
