# Generated by Django 5.2.1 on 2025-10-03 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_common", "0004_delete_toolsubscription"),
        ("tools_memory", "0002_alter_memoryitem_toolcall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="next_version",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="prev_version",
                to="tools_memory.memoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="toolCall",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="memoryItems",
                to="tools_common.toolcall",
            ),
        ),
    ]
