# Generated by Django 5.2.7 on 2025-10-22 15:47

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0023_alter_conversationmessagepart_toolcall_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KVItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("value", models.JSONField()),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent instance that owns this key-value item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kv_items",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="builtin_kv_storage.kvitem",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="builtin_kv_storage.kvitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key-Value Item",
                "verbose_name_plural": "Key-Value Items",
                "ordering": ["key"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
