# Generated by Django 5.2.1 on 2025-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcall",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="toolresponse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
