# Generated by Django 5.2.1 on 2025-10-01 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools_common", "0003_toolsubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ToolSubscription",
        ),
    ]
