# Generated by Django 5.2.1 on 2025-10-04 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0004_system_os"),
        ("tools_common", "0004_delete_toolsubscription"),
        ("tools_mcp", "0003_mcpserver_transport_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the tool, e.g., 'apple-mcp'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly name, e.g., 'Apple MCP'.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of what the tool does.",
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an internal tool (Python, Shell), False for external MCP tools.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an internal tool (Python, Shell), False for external MCP tools.",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP Socket (HTTP/S)"),
                            ("stdin_stdout", "Standard I/O (stdin/stdout)"),
                        ],
                        default="tcp",
                        help_text="The communication transport type for this tool.",
                        max_length=20,
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        blank=True,
                        help_text="The Git repository URL for external tools.",
                        null=True,
                    ),
                ),
                (
                    "manifest",
                    models.JSONField(
                        blank=True,
                        help_text="The parsed manifest.json file from the repository.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ToolInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_installed", "Not Installed"),
                            ("installing", "Installing"),
                            ("installed", "Installed"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="not_installed",
                        max_length=20,
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        help_text="The installation path on the remote system.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "process_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The PID of the running tool process on the remote system.",
                        null=True,
                    ),
                ),
                (
                    "assigned_port",
                    models.IntegerField(
                        blank=True,
                        help_text="The network port assigned to the running service.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mcp_server",
                    models.OneToOneField(
                        blank=True,
                        help_text="The MCPServer that this ToolInstallation manages the connection for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installation",
                        to="tools_mcp.mcpserver",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_installations",
                        to="systems.system",
                    ),
                ),
                (
                    "tool_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="tools_common.tooldefinition",
                    ),
                ),
            ],
            options={
                "unique_together": {("tool_definition", "system")},
            },
        ),
        migrations.CreateModel(
            name="ToolInstallationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("error", "Error")],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "tool_installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tools_common.toolinstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
