# Generated by Django 5.2.1 on 2025-10-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_common", "0005_tooldefinition_toolinstallation_toolinstallationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooldefinition",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Globally enable or disable this tool for all agents.",
            ),
        ),
    ]
