# Generated by Django 5.2.1 on 2025-10-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_common", "0006_alter_tooldefinition_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tooldefinition",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the manifest was last checked for updates.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tooldefinition",
            name="manifest_version",
            field=models.CharField(
                blank=True,
                help_text="The version from the tool's manifest file.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tooldefinition",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("updating", "Updating"),
                    ("up_to_date", "Up to Date"),
                    ("error", "Error"),
                    ("unknown", "Unknown"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
