# Generated by Django 5.2.1 on 2025-10-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0004_system_os"),
        ("tools_common", "0007_tooldefinition_last_checked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tooldefinition",
            name="available_on_all_systems",
            field=models.BooleanField(
                default=True,
                help_text="If true, this tool is available on all compatible systems by default.",
            ),
        ),
        migrations.AddField(
            model_name="tooldefinition",
            name="available_on_systems",
            field=models.ManyToManyField(
                blank=True,
                help_text="A specific list of systems where this tool is available.",
                related_name="tool_definitions",
                to="systems.system",
            ),
        ),
    ]
