# Generated by Django 5.2.1 on 2025-10-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0010_agent_available_tools"),
        ("systems", "0004_system_os"),
        ("tools_common", "0008_tooldefinition_available_on_all_systems_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="toolinstallation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tooldefinition",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("shared", "Shared Process"),
                    ("dedicated", "Dedicated Process per Instance"),
                ],
                default="shared",
                help_text="Determines if one process is shared across a system or if each agent instance gets a dedicated process.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="toolinstallation",
            name="agent_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific agent instance this installation is dedicated to. Null for shared tools.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_installations",
                to="agent.agentinstance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="toolinstallation",
            unique_together={("tool_definition", "system", "agent_instance")},
        ),
    ]
