import pytest
import os
from unittest.mock import MagicMock
from launcher.management.commands.server import Command

# By marking this with pytest.mark.django_db, we get access to the Django database
# and settings, even though this specific test doesn't use the DB directly.
# It's good practice for most Django-related tests.
@pytest.mark.django_db
def test_read_local_config_success():
    """
    Tests that _read_local_config correctly parses a valid config file.
    """
    # 1. Arrange: Create a temporary fake config file
    config_content = """
# This is a comment
LISTEN_ADDRESS = "127.0.0.1"
LISTEN_PORT = '8888' # A port number as a string
SECRET_KEY = "a-secret-key"

# An empty line above
INVALID_LINE_NO_EQUALS
"""
    # Use a temporary directory provided by pytest's tmp_path fixture
    # This is safer and cleaner than creating files manually.
    fake_config_path = "test_settings_local.py"
    with open(fake_config_path, "w") as f:
        f.write(config_content)

    # Instantiate the command
    command = Command()
    command.stdout = MagicMock() # Mock stdout to prevent printing during tests
    command.style = MagicMock()

    try:
        # 2. Act: Call the method we want to test
        parsed_config = command._read_local_config(fake_config_path)

        # 3. Assert: Check if the output is what we expect
        assert parsed_config is not None
        assert isinstance(parsed_config, dict)
        assert len(parsed_config) == 3  # Should ignore comments, empty lines, and invalid lines
        assert parsed_config["LISTEN_ADDRESS"] == "127.0.0.1"
        assert parsed_config["LISTEN_PORT"] == "8888"
        assert parsed_config["SECRET_KEY"] == "a-secret-key"
        assert "INVALID_LINE_NO_EQUALS" not in parsed_config

    finally:
        # 4. Cleanup: Remove the temporary file
        if os.path.exists(fake_config_path):
            os.remove(fake_config_path)

def test_read_local_config_file_not_found():
    """
    Tests that _read_local_config returns an empty dict if the file doesn't exist.
    """
    # 1. Arrange
    command = Command()
    command.stdout = MagicMock()
    command.style = MagicMock()
    non_existent_path = "non_existent_file.py"

    # 2. Act
    parsed_config = command._read_local_config(non_existent_path)

    # 3. Assert
    assert parsed_config is not None
    assert isinstance(parsed_config, dict)
    assert len(parsed_config) == 0
def test_write_local_config_success(tmp_path):
    """
    Tests that _write_local_config correctly writes configuration to a file.
    """
    # 1. Arrange
    config_data = {
        "LISTEN_ADDRESS": "127.0.0.1",
        "LISTEN_PORT": "8001",
        "SECRET_KEY": "my-test-secret"
    }
    test_config_path = tmp_path / "test_settings_local_output.py"

    command = Command()
    command.stdout = MagicMock()
    command.style = MagicMock()

    # 2. Act
    command._write_local_config(str(test_config_path), config_data)

    # 3. Assert
    assert test_config_path.exists()
    content = test_config_path.read_text()

    expected_content_lines = [
        "# This file is automatically generated by 'manage.py server setup'.",
        "# Do not edit it manually unless you know what you are doing.",
        "",
        "LISTEN_ADDRESS = '127.0.0.1'",
        "LISTEN_PORT = '8001'",
        "SECRET_KEY = 'my-test-secret'",
        "" # fs_write implicitly adds a newline at the end if the last line of content has one
    ]
    expected_content = "\n".join(expected_content_lines)

    assert content == expected_content
    command.stdout.write.assert_called_with(f"\nWriting configuration to {test_config_path}...")
