# Generated by Django 5.2.1 on 2025-10-06 01:44

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FsLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                ("is_newest_version", models.BooleanField(db_index=True, default=True)),
                ("path", models.CharField(max_length=512)),
                ("filter", models.CharField(default=None, max_length=4096, null=True)),
                ("recursive", models.BooleanField(default=False)),
                (
                    "load_mode",
                    models.CharField(
                        db_index=True, default=None, max_length=16, null=True
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_directory", models.BooleanField(default=False)),
                ("exists_on_fs", models.BooleanField(default=False)),
                ("fs_created", models.DateTimeField(default=None, null=True)),
                ("fs_modified", models.DateTimeField(default=None, null=True)),
                ("fs_lastread", models.DateTimeField(default=None, null=True)),
                ("fs_size", models.IntegerField(default=0)),
                ("action", models.CharField(max_length=16)),
                ("content_diff", models.TextField(default=b"", max_length=10485760)),
                ("stored_as", models.CharField(max_length=16)),
                ("summary", models.CharField(blank=True, default=None, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "prev_version",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_versions",
                        to="buildin_filesystem.fslogentry",
                    ),
                ),
                (
                    "reverted_from_entry",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverted_by_entries",
                        to="buildin_filesystem.fslogentry",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="calls.toolcall",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
