# Generated by Django 5.2.7 on 2025-10-09 05:32

import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0002_initial"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentToAgentDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                ("description", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_logs",
                        to="agents.agent",
                    ),
                ),
                (
                    "agent_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_logs",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_logs",
                        to="calls.toolcall",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AgentToAgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                (
                    "receiver_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_inter_agent_messages",
                        to="agents.agent",
                    ),
                ),
                (
                    "receiver_agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_inter_agent_messages",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "receiver_conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_inter_agent_messages",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "sender_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_inter_agent_messages",
                        to="agents.agent",
                    ),
                ),
                (
                    "sender_agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_inter_agent_messages",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "sender_conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_inter_agent_messages",
                        to="agents.conversationmessage",
                    ),
                ),
                (
                    "sender_toolCall",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_inter_agent_messages",
                        to="calls.toolcall",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AgentToAgentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "can_send",
                    models.BooleanField(
                        default=False, help_text="Source can send messages to Target"
                    ),
                ),
                (
                    "can_receive",
                    models.BooleanField(
                        default=False,
                        help_text="Source can receive messages from Target",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_permissions",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_permissions",
                        to="agents.agentinstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("source_instance", "target_instance")},
            },
        ),
    ]
