# Generated by Django 5.2.7 on 2025-10-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_a2a", "0004_alter_agenttoagentdescription_raw_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttoagentdescription",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="builtin_a2a.agenttoagentdescription",
            ),
        ),
        migrations.AlterField(
            model_name="agenttoagentmessage",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="builtin_a2a.agenttoagentmessage",
            ),
        ),
    ]
