# Generated by Django 5.2.7 on 2025-10-09 05:32

import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0002_initial"),
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                (
                    "subscription_id",
                    models.CharField(
                        help_text="A unique identifier for the subscription, provided by the agent.",
                        max_length=128,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="The name of the tool to execute (e.g., 'python', 'shell').",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_subscriptions",
                        to="agents.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_subscriptions",
                        to="agents.agentinstance",
                    ),
                ),
                (
                    "creating_tool_call",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subscriptions",
                        to="calls.toolcall",
                    ),
                ),
            ],
            options={
                "unique_together": {("agentInstance", "subscription_id")},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
