# Generated by Django 5.2.7 on 2025-10-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_subscriptions", "0005_alter_toolsubscription_fork_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolsubscription",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="builtin_subscriptions.toolsubscription",
            ),
        ),
        migrations.AlterField(
            model_name="toolsubscription",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="builtin_subscriptions.toolsubscription",
            ),
        ),
    ]
