# Generated by Django 5.2.9 on 2026-05-08 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("builtin_filesystem", "0001_initial"),
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fslogentry",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="server.agentmodel",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="agent_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="server.instancemodel",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="conversationMessage",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="server.conversationmessage",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="builtin_filesystem.fslogentry",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="prev_version",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_versions",
                to="builtin_filesystem.fslogentry",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="builtin_filesystem.fslogentry",
            ),
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="reverted_from_entry",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reverted_by_entries",
                to="builtin_filesystem.fslogentry",
            ),
        ),
    ]
