# Generated by Django 5.2.9 on 2026-04-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_filesystem", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fslogentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="fslogentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
