# Generated by Django 5.2.7 on 2025-10-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_agent_fork_of_agent_raw_data_reference_and_more"),
        ("builtin_filesystem", "0003_fslogentry_fork_of_fslogentry_raw_data_reference"),
        ("calls", "0003_toolcall_fork_of_toolcall_raw_data_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fslogentry",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="agents.agent",
            ),
        ),
        migrations.AlterField(
            model_name="fslogentry",
            name="agentInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="agents.agentinstance",
            ),
        ),
        migrations.AlterField(
            model_name="fslogentry",
            name="conversationMessage",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="agents.conversationmessage",
            ),
        ),
        migrations.AlterField(
            model_name="fslogentry",
            name="toolCall",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsLogEntries",
                to="calls.toolcall",
            ),
        ),
    ]
