# Generated by Django 5.2.7 on 2025-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_filesystem", "0004_alter_fslogentry_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fslogentry",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
