"""Message and MessagePart models representing conversation turns."""
from __future__ import annotations

from typing import Any

from django.db import models
from django_enum import EnumField
from jinja2 import BaseLoader, Environment

from server.models.base_model import BaseModel
from server.models.content import GenericContent
from server.models.enums.message_enums import (
    MessageContentType,
    MessagePartType,
    MessageRole,
    MessageSource,
)
from server.models.queries.response import Response
_JINJA_ENV = Environment(loader=BaseLoader())


class Message(BaseModel):
    """A single message within a conversation session."""

    session = models.ForeignKey( "server.SessionModel", on_delete=models.CASCADE, related_name="related_messages")
    session_version: models.ForeignKey | None = models.ForeignKey( "server.SessionVersionModel", on_delete=models.CASCADE, related_name="related_messages")

    # If the message was generated by an LLM response
    response: Response | None = models.ForeignKey(Response, null=True, blank=True, on_delete=models.CASCADE,  related_name="related_messages")

    prev_message: models.ForeignKey | None = models.ForeignKey( "self", null=True, blank=True, on_delete=models.SET_NULL, related_name="next_messages")

    role: str = models.CharField(choices=MessageRole.choices, default=MessageRole.USER, max_length=61)
    source: str = models.CharField(choices=MessageSource.choices, default=MessageSource.default, max_length=61)

    hide_from_context: bool = models.BooleanField(default=False)
    pin_to_context: bool = models.BooleanField(default=False)

    observable_fields = set([
        "pk",
        "session_version",
    ])

    @property
    def observable_keys(self):
        k = f"Message:{self.pk}",
        k = f"SessionModel:{self.session_pk}.related_messages"
        k = f"SessionVersionModel:{self.session_version_pk}.related_messages"

        return set([
            "Message",
            f"Message.pk:{self.pk}",
            f"Message.session_version:{self.session_version_pk}",        
        ])


    def add_part( self, type: str, content_type: MessageContentType, content: Any, template_data: Any = None, tool_call: Any = None) -> MessagePart:
        """Create and return a new :class:`MessagePart` attached to this message.

        Parameters
        ----------
        type:
            Part type key (``"message"``, ``"reasoning"``, ``"toolcall"``).
        content_type:
            Content type enum value (text, image, template, json).
        content:
            Raw content value or a :class:`GenericContent` instance.  When
            ``content_type`` is ``IMAGE``, TEXT or JSON and ``content`` is not
            already a :class:`GenericContent`, one is created automatically.
        template_data:
            Optional template data (string or :class:`GenericContent`).  Used
            when ``content_type`` is ``TEMPLATE``.
        tool_call:
            Optional associated :class:`~server.models.tasks.task_definition_version.ToolCall`
            instance.  Used when ``type`` is ``"toolcall"``.
        """
        if not isinstance(content, GenericContent):
            if content_type.upper() == MessageContentType.IMAGE:
                content = GenericContent.from_image(content)
            elif content_type.upper() in (
                MessageContentType.TEMPLATE,
                MessageContentType.TEXT,
            ):
                content = GenericContent.from_text(content)
            elif content_type.upper() == MessageContentType.JSON:
                content = GenericContent.from_data(content)
            else:
                raise Exception(f"unknown content type {content_type}")

        if template_data and not isinstance(template_data, GenericContent):
            template_data = GenericContent.from_data(template_data)

        return MessagePart.objects.create(
            message=self,
            type=MessagePartType[type.upper()],
            content=content,
            content_type=MessageContentType[content_type.upper()],
            template_data=template_data,
            tool_call=tool_call,
        )

    def save(self, *args: Any, **kwargs: Any) -> Any:
        """Ensure ``pin_to_context`` and ``hide_from_context`` are not both
        ``True`` (pin wins)."""
        if self.hide_from_context is True and self.pin_to_context is True:
            self.pin_to_context = False
        return super().save(*args, **kwargs)


class MessagePart(BaseModel):
    """A single part within a :class:`Message`, representing e.g. text content,
    an image, a tool call, or a reasoning block."""

    message: models.ForeignKey | None = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="parts" )

    tokens: int = models.IntegerField(default=0)
    type: MessagePartType = EnumField(MessagePartType, default=MessagePartType.MESSAGE)

    content: GenericContent | None = models.ForeignKey( GenericContent, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT, related_name="conversation_message_parts_content")
    content_type: MessageContentType = EnumField( MessageContentType, default=MessageContentType.TEXT)
    template_data: GenericContent | None = models.ForeignKey( GenericContent, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT, related_name="conversation_message_parts_template")

    tool_call: models.OneToOneField | None = models.OneToOneField( "server.AgentTaskCall", on_delete=models.CASCADE, default=None, blank=True, null=True)

    def to_string(self):
        if self.content_type == MessageContentType.TEMPLATE:
            try:
                context = self.template_data.get() if self.template_data else {}
                return _JINJA_ENV.from_string(self.content.get() if self.content else "").render(**context)
            except Exception as e:
                  return [{"type": "text", "text": f"Error in Template String:{e}\n{self.content.get()}"}]

        if self.content_type == MessageContentType.JSON:
            return self.content.get()
        if self.content_type == MessageContentType.TEXT:
            return self.content.get()
        if self.content_type == MessageContentType.IMAGE:
            return self.content.get()
        