from django.db import models
from django_enum import EnumField
from server.models.enums.message_enums import MessagePartType, MessageRole, MessageSource
from server.models.base_model import BaseModel
from server.models.content import GenericContent
from server.models.enums.message_enums import MessageContentType
from server.models.queries.response import Response

class Message(BaseModel):
    session_version = models.ForeignKey("server.SessionVersionModel", on_delete=models.CASCADE, related_name="related_messages")
    
    # if  message was generated by a llm response
    response       = models.ForeignKey(Response     , null=True, blank=True, on_delete=models.CASCADE, related_name='related_messages')  
    
    prev_message   = models.ForeignKey("self"     , null=True, blank=True, on_delete=models.CASCADE, related_name='next_messages')

    tool_calls     = models.ManyToManyField("server.AgentTaskCall",related_name='related_messages')
    index          = models.FloatField(default=0)

    role = models.CharField(choices=MessageRole.choices, default=MessageRole.USER, max_length=61)
    source = models.CharField(choices=MessageSource.choices, default=MessageSource.default, max_length=61)

    hide_from_context = models.BooleanField(default=False)
    pin_to_context = models.BooleanField(default=False)
    
    class Meta:
        ordering = ("index","pk")

    def add_part(self, type:str, content_type:MessageContentType, content, template_data=None, tool_call=None):
        '''
            Parts is dict with minimal keys:
                type: message, reasoning, toolcall
                content_type: text|image|template|json
                content: str|dict
            In case Part.content_type is template the following keys are also needed:
                template_data: dict
            if case Part.type is "toolcall":
                tool_call: ToolCall
        '''
        if not isinstance(content, GenericContent):
            if content_type == "image":
                content = GenericContent.from_image(content)
            elif content_type == "template" or content_type == "text":
                content = GenericContent.from_text(content)
            elif content_type == "json":
                content = GenericContent.from_data(content)
            else:
                raise Exception(f"unknown content type {content_type}")
            
        if template_data and not isinstance(template_data, GenericContent):
            template_data = GenericContent.from_text(template_data)
          
        args = {
            "type":  MessagePartType[type.upper()],
            "message": self,
            "content": content,
            "content_type": MessageContentType[content_type.upper()],
        }

        if args["content_type"] == MessageContentType.TEMPLATE:
            args["content_template"] = template_data
        
        if tool_call:
            args["tool_call"] = tool_call
            
        return MessagePart.objects.create(**args)
        
    def save(self, *args, **kwargs):
        if self.hide_from_context is True and self.pin_to_context is True:
            self.pin_to_context = False
        super().save(*args, **kwargs)




class MessagePart(BaseModel):
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name='parts')

    tokens = models.IntegerField(default=0)
    type     = EnumField(MessagePartType, default=MessagePartType.MESSAGE)

    content          = models.ForeignKey(GenericContent, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT, related_name="conversation_message_parts_content")
    content_type     = EnumField(MessageContentType, default=MessageContentType.TEXT)
    content_template = models.ForeignKey(GenericContent, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT, related_name="conversation_message_parts_template")

    tool_call     = models.OneToOneField("server.AgentTaskCall", on_delete=models.CASCADE, default=None, blank=True, null=True)

    class Meta:
        ordering = ("pk")