# Generated by Django 5.2.1 on 2025-09-20 18:20

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("agent_pk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "model",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="providers.model",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owned_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AgentInstance",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("instance_pk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("IDLE_AUTOMATED", "Idle (Automated)"),
                            ("THINKING", "Thinking"),
                            ("EXECUTING_TOOLS", "Executing Tools"),
                            ("AWAITING_USER_INPUT", "Awaiting User Input"),
                            ("AWAITING_AGENT_MESSAGE", "Awaiting Agent Message"),
                            ("FINISHED", "Finished"),
                            ("ERROR", "Error"),
                            ("MISCONFIGURED", "Misconfigured"),
                            ("SYSTEM_OFFLINE", "System Offline"),
                        ],
                        default="IDLE",
                        max_length=30,
                    ),
                ),
                ("workingdir", models.CharField(default="", max_length=1024)),
                ("require_user_interaction", models.BooleanField(default=False)),
                ("limit_max_conversation_messages", models.IntegerField(default=20)),
                ("limit_max_memory_items", models.IntegerField(default=15)),
                ("limit_max_automated_steps", models.IntegerField(default=0)),
                ("automated_step_count", models.IntegerField(default=0)),
                (
                    "workingdir_write_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="Allow write operations within the working directory.",
                    ),
                ),
                (
                    "access_rules",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fine-grained access rules, one per line. E.g., 'path/to/deny', '!path/to/allow', '[read-only] path/to/readonly'.",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="agent.agent",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_instances",
                        to="providers.model",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        help_text="The system this instance is assigned to run on.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_instances",
                        to="systems.system",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DebugLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("event", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=16)),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debugLogEntries",
                        to="agent.agentinstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LLMQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmqueries",
                        to="agent.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmqueries",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "apikey",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llmqueries",
                        to="providers.apikey",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmqueries",
                        to="providers.model",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LLMResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("prompt_tokens", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmResponses",
                        to="agent.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmResponses",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "llmQuery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmResponses",
                        to="agent.llmquery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("role", models.CharField(max_length=32)),
                (
                    "agent",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversationMessages",
                        to="agent.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversationMessages",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "llmResponse",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversationMessages",
                        to="agent.llmresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoryLimitingRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_name",
                    models.CharField(
                        default="default",
                        help_text="Name of tool or other group this limit belongs to",
                        max_length=255,
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        help_text="The unique name of the rule template to override (e.g., 'fs_by_path').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of why this override exists.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lower numbers run first (not currently used, for future extension).",
                    ),
                ),
                (
                    "limit_success",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for successful calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "limit_failed",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for failed calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "limit_pending",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for pending calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "limit_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override for total calls. Blank uses tool default.",
                        null=True,
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_limiting_rules",
                        to="agent.agentinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "group_name", "rule_name"],
                "unique_together": {("agentInstance", "group_name", "rule_name")},
            },
        ),
        migrations.CreateModel(
            name="InstancePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "can_send",
                    models.BooleanField(
                        default=False, help_text="Source can send messages to Target"
                    ),
                ),
                (
                    "can_receive",
                    models.BooleanField(
                        default=False,
                        help_text="Source can receive messages from Target",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_permissions",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_permissions",
                        to="agent.agentinstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("source_instance", "target_instance")},
            },
        ),
    ]
