# Generated by Django 5.2.1 on 2025-09-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmquery",
            name="status",
            field=models.CharField(default="pending"),
        ),
    ]
