# Generated by Django 5.2.1 on 2025-09-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_llmquery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmresponse",
            name="status",
            field=models.CharField(default="pending"),
        ),
    ]
