# Generated by Django 5.2.1 on 2025-09-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0003_llmresponse_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessage",
            name="hide_from_context",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="pin_to_context",
            field=models.BooleanField(default=False),
        ),
    ]
