# Generated by Django 5.2.1 on 2025-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0004_conversationmessage_hide_from_context_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstance",
            name="access_rules",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Fine-grained access rules, one per line. E.g., '!path/to/deny', '>path/to/allow', '</path/to/readonly'.",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="debuglogentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historylimitingrule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="llmresponse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="InstancePermission",
        ),
    ]
