# Generated by Django 5.2.1 on 2025-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0005_alter_agentinstance_access_rules_and_more"),
        
        ("tools_common", "0005_tooldefinition_toolinstallation_toolinstallationlog")
    ]

    operations = [
        
        migrations.AddField(
            model_name="agent",
            name="available_tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents_using_this_tool",
                to="tools_common.tooldefinition",
            ),
        ),
    ]
