# Generated by Django 5.2.1 on 2025-10-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0006_agent_available_tools"),
        ("tools_common", "0008_tooldefinition_available_on_all_systems_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="available_tools",
            field=models.ManyToManyField(
                related_name="agents_using_this_tool", to="tools_common.tooldefinition"
            ),
        ),
    ]
