# Generated by Django 5.2.1 on 2025-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0007_alter_agent_available_tools"),
        ("tools_common", "0008_tooldefinition_available_on_all_systems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="available_tools",
        ),
        migrations.AddField(
            model_name="agent",
            name="available_tools_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents_using_this_tool",
                to="tools_common.tooldefinition",
            ),
        ),
    ]
