# Generated by Django 5.2.1 on 2025-10-04 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0008_remove_agent_available_tools_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="available_tools_new",
        ),
    ]
