# Generated by Django 5.2.1 on 2025-09-20 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent", "0001_initial"),
        ("tools_common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FsLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_newest_version", models.BooleanField(db_index=True, default=True)),
                ("path", models.CharField(max_length=512)),
                ("filter", models.CharField(default=None, max_length=4096, null=True)),
                ("recursive", models.BooleanField(default=False)),
                ("is_loaded", models.BooleanField(db_index=True, default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_directory", models.BooleanField(default=False)),
                ("exists_on_fs", models.BooleanField(default=False)),
                ("fs_created", models.DateTimeField(default=None, null=True)),
                ("fs_modified", models.DateTimeField(default=None, null=True)),
                ("fs_lastread", models.DateTimeField(default=None, null=True)),
                ("fs_size", models.IntegerField(default=0)),
                ("action", models.CharField(max_length=16)),
                ("content_diff", models.TextField(default=b"", max_length=10485760)),
                ("stored_as", models.CharField(max_length=16)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="agent.agent",
                    ),
                ),
                (
                    "agentInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "conversationMessage",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="agent.conversationmessage",
                    ),
                ),
                (
                    "prev_version",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_version",
                        to="tools_filesystem.fslogentry",
                    ),
                ),
                (
                    "toolCall",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fsFileLogEntries",
                        to="tools_common.toolcall",
                    ),
                ),
            ],
        ),
    ]
