# Generated by Django 5.2.1 on 2025-09-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_filesystem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fslogentry",
            name="summary",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
