# Generated by Django 5.2.1 on 2025-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_filesystem", "0002_fslogentry_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fslogentry",
            name="is_loaded",
        ),
        migrations.AddField(
            model_name="fslogentry",
            name="load_mode",
            field=models.CharField(
                db_index=True, default=None, max_length=16, null=True
            ),
        ),
    ]
