# Generated by Django 5.2.1 on 2025-09-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_filesystem", "0003_remove_fslogentry_is_loaded_fslogentry_load_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fslogentry",
            name="summary",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
