# Generated by Django 5.2.1 on 2025-09-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_filesystem", "0004_alter_fslogentry_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="fslogentry",
            name="reverted_from_entry",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reverted_by_entries",
                to="tools_filesystem.fslogentry",
            ),
        ),
        migrations.AlterField(
            model_name="fslogentry",
            name="prev_version",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_versions",
                to="tools_filesystem.fslogentry",
            ),
        ),
    ]
