# Generated by Django 5.2.7 on 2025-10-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0003_toolcall_fork_of_toolcall_raw_data_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcall",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="IDLE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="toolresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="IDLE",
                max_length=32,
            ),
        ),
    ]
