# Generated by Django 5.2.7 on 2025-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0004_alter_toolcall_status_alter_toolresponse_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcall",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
        migrations.AlterField(
            model_name="toolresponse",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
