# Generated by Django 5.2.7 on 2025-10-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0005_alter_toolcall_raw_data_alter_toolresponse_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcall",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="calls.toolcall",
            ),
        ),
        migrations.AlterField(
            model_name="toolresponse",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="calls.toolresponse",
            ),
        ),
    ]
