# Generated by Django 5.2.7 on 2025-10-31 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0030_remove_conversationmessagepart_promptvariant_and_more"),
        ("calls", "0007_alter_toolcall_fork_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcall",
            name="conversationMessagePart",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="toolCalls",
                to="agents.conversationmessagepart",
            ),
        ),
    ]
