# Generated by Django 5.2.7 on 2025-10-09 05:32

import datetime
import dirtyfields.dirtyfields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("definitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("stopping", "Stopping"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="starting",
                        help_text="Current runtime status of the tool instance.",
                        max_length=20,
                    ),
                ),
                (
                    "process_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The PID of the running tool process on the remote system.",
                        null=True,
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        help_text="The full URL of the tool's endpoint (if applicable).",
                        max_length=2000,
                        null=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Stores the last runtime error message.",
                        null=True,
                    ),
                ),
                (
                    "tool_installation",
                    models.ForeignKey(
                        help_text="The ToolInstallation this instance belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="definitions.toolinstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
