# Generated by Django 5.2.1 on 2025-10-06 01:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("definitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A user-friendly name for the MCP server.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        help_text="The full URL of the MCP endpoint (must be HTTP or HTTPS). Required for TCP transport.",
                        max_length=2000,
                        null=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP Socket (HTTP/S)"),
                            ("stdin_stdout", "Standard I/O (stdin/stdout)"),
                        ],
                        default="tcp",
                        help_text="The communication transport type for the MCP server.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                            ("connecting", "Connecting..."),
                        ],
                        default="disconnected",
                        help_text="Current connection status of the MCP server.",
                        max_length=20,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Stores the last connection or tool-listing error message.",
                        null=True,
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of available tools discovered from the endpoint.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this MCP server's tools are enabled for agents.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool_installation",
                    models.OneToOneField(
                        blank=True,
                        help_text="The ToolInstallation that manages this MCP server instance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_server_connection",
                        to="definitions.toolinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Server",
                "verbose_name_plural": "MCP Servers",
            },
        ),
    ]
