# Generated by Django 5.2.1 on 2025-10-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolinstance",
            name="raw_data",
            field=models.TextField(default="", max_length=104857600),
        ),
    ]
