# Generated by Django 5.2.1 on 2025-10-06 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0002_toolinstance_raw_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toolinstance",
            options={},
        ),
    ]
