# Generated by Django 5.2.7 on 2025-10-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0002_alter_toolinstance_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolinstance",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="instances.toolinstance",
            ),
        ),
        migrations.AddField(
            model_name="toolinstance",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="instances.toolinstance",
            ),
        ),
    ]
