# Generated by Django 5.2.7 on 2025-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0003_toolinstance_fork_of_toolinstance_raw_data_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolinstance",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
