# Generated by Django 5.2.9 on 2026-03-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprofile",
            name="variant_defs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="query",
            name="agent_instance_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_queries",
                to="server.agentinstanceversion",
            ),
        ),
    ]
