# Generated by Django 5.2.9 on 2026-05-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdefinition",
            name="commit",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
