# Generated by Django 5.2.9 on 2026-05-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_taskdefinition_commit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentversionsubagentrelation",
            name="parent_agent_version",
        ),
        migrations.RemoveField(
            model_name="agentversionsubagentrelation",
            name="sub_agent_version",
        ),
        migrations.AddField(
            model_name="skill",
            name="latest_skill_version",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_newest_skill",
                to="server.skillversion",
            ),
        ),
        migrations.DeleteModel(
            name="AgentVersionAvailableTool",
        ),
        migrations.DeleteModel(
            name="AgentVersionSubAgentRelation",
        ),
    ]
