# Generated by Django 5.2.9 on 2026-03-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_agentprofile_variant_defs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="limit_parallel_calls",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apikey",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="limit_request_per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apikey",
            name="limit_request_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apikey",
            name="limit_tokens_per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apikey",
            name="limit_tokens_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apiprovider",
            name="limit_parallel_calls",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agenttaskrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("QUEUED", "Queued"),
                    ("ACTIVE", "Active"),
                    ("WAITING_RESULTTASKS", "Waiting for result tasks"),
                    ("RATE_LIMITED", "Rate limited — waiting for LLM capacity"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                ],
                default="NEW",
                max_length=61,
            ),
        ),
    ]
