# Generated by Django 5.2.9 on 2026-05-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0003_remove_agentversionsubagentrelation_parent_agent_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="parent_skill",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_skills",
                to="server.skill",
            ),
        ),
    ]
