# Generated by Django 5.2.9 on 2026-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_aimodel_limit_parallel_calls_apikey_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agenttaskcall",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agenttaskdefinition",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agenttaskinstance",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agenttaskrun",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
