# Generated by Django 5.2.9 on 2026-05-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_skill_parent_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="parent_agent",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="parent_project",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="parent_skill",
        ),
        migrations.AddField(
            model_name="skillversion",
            name="parent_agent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_skills",
                to="server.agentmodel",
            ),
        ),
        migrations.AddField(
            model_name="skillversion",
            name="parent_project",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_skills",
                to="server.project",
            ),
        ),
        migrations.AddField(
            model_name="skillversion",
            name="parent_skill",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_skills",
                to="server.skill",
            ),
        ),
    ]
