# Generated by Django 5.2.9 on 2026-03-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_agentprofile_priority_agenttaskcall_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentinstance",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="agentversion",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="agentversion",
            name="subagent_names",
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_agent_instances",
                to="server.agentinstance",
            ),
        ),
        migrations.AddField(
            model_name="agentinstanceversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_agent_instance_versions",
                to="server.agentinstanceversion",
            ),
        ),
        migrations.AddField(
            model_name="agentinstanceversion",
            name="display_name",
            field=models.CharField(
                blank=True, default=None, max_length=2048, null=True
            ),
        ),
    ]
