# Generated by Django 5.2.9 on 2026-03-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_remove_agentinstance_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttaskdefinition",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("CHAT", "Chat"),
                    ("COMMAND", "Command"),
                    ("TASK", "Task"),
                    ("TOOL", "Tool"),
                    ("CHAIN", "Chain"),
                    ("GROUP", "Group"),
                    ("CHORD", "Chord"),
                    ("MAP", "Map"),
                    ("WEBAPI", "Webapi"),
                ],
                max_length=20,
            ),
        ),
    ]
