# Generated by Django 5.2.9 on 2026-05-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_remove_skill_parent_agent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillversion",
            name="parent_agent",
        ),
        migrations.AddField(
            model_name="skillversion",
            name="parent_agent1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_skills",
                to="server.agentmodel",
            ),
        ),
    ]
