# Generated by Django 5.2.9 on 2026-05-09 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_remove_skillversion_parent_agent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skillversion",
            old_name="parent_agent1",
            new_name="parent_agent",
        ),
    ]
