# Generated by Django 5.2.9 on 2026-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_alter_agenttaskdefinition_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="tool_calls",
            field=models.ManyToManyField(
                related_name="related_responses", to="server.agenttaskcall"
            ),
        ),
    ]
