# Generated by Django 5.2.9 on 2026-03-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0007_response_tool_calls"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentVersionSubAgentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent_class", models.CharField(max_length=255)),
                ("create_option", models.CharField(max_length=255)),
                ("visible_to", models.CharField(max_length=255)),
                ("instance_name", models.CharField(max_length=255)),
                (
                    "parent_agent_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subagent_relations",
                        to="server.agentversion",
                    ),
                ),
                (
                    "sub_agent_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_agent_relations",
                        to="server.agentversion",
                    ),
                ),
            ],
        ),
    ]
