# Generated by Django 5.2.9 on 2026-05-10 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_filesystem", "0002_initial"),
        ("server", "0008_remove_skillversion_parent_agent_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstanceModel",
            new_name="SessionModel",
        ),
        migrations.RemoveField(
            model_name="query",
            name="agent_profile",
        ),
    ]
