# Generated by Django 5.2.9 on 2026-03-29 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0008_agentversionsubagentrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentversionsubagentrelation",
            name="agent_class",
        ),
    ]
