# Generated by Django 5.2.9 on 2026-05-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0009_rename_instancemodel_sessionmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="", max_length=10000)),
                ("path", models.CharField(max_length=255)),
            ],
        ),
    ]
