# Generated by Django 5.2.9 on 2026-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0009_remove_agentversionsubagentrelation_agent_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="enable_thinking",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="agenttaskdefinition",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("CHAT", "Chat"),
                    ("COMMAND", "Command"),
                    ("TASK", "Task"),
                    ("TOOL", "Tool"),
                    ("CHAIN", "Chain"),
                    ("GROUP", "Group"),
                    ("CHORD", "Chord"),
                    ("MAP", "Map"),
                    ("WEBAPI", "Webapi"),
                    ("WEBVIEW", "Webview"),
                ],
                max_length=20,
            ),
        ),
    ]
