# Generated by Django 5.2.9 on 2026-05-10 23:49

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0010_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentversionmodel",
            name="agent_profile",
        ),
        migrations.RemoveField(
            model_name="response",
            name="agent_profile",
        ),
        migrations.RemoveField(
            model_name="agenttaskrun",
            name="agent_profile",
        ),
        migrations.CreateModel(
            name="SettingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("thinking", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=0)),
                ("max_task_steps", models.IntegerField(default=0)),
                ("unattended_steps", models.IntegerField(default=0)),
                ("max_history_messages", models.IntegerField(default=0)),
                ("priority", models.IntegerField(default=0)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("interrupt", "Interrupt"),
                            ("queue", "Queue"),
                            ("merge", "Merge"),
                            ("parallel", "Parallel"),
                        ],
                        default="queue",
                        max_length=20,
                    ),
                ),
                (
                    "tool_call_syntax",
                    models.CharField(
                        choices=[
                            ("default", "Default (OpenAI style)"),
                            ("custom", "Custom tagging"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("commandNames", models.JSONField(blank=True, default=list)),
                ("disallowedCommandNames", models.JSONField(blank=True, default=list)),
                ("taskNames", models.JSONField(blank=True, default=list)),
                ("disallowedTaskNames", models.JSONField(blank=True, default=list)),
                ("toolNames", models.JSONField(blank=True, default=list)),
                ("disallowedToolNames", models.JSONField(blank=True, default=list)),
                ("skillNames", models.JSONField(blank=True, default=list)),
                ("disallowedSkillNames", models.JSONField(blank=True, default=list)),
                (
                    "extra_settings",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("commit", models.TextField(default="", max_length=1024)),
                (
                    "aimodel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_agent_settings",
                        to="server.aimodel",
                    ),
                ),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="server.settingsmodel",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="server.settingsmodel",
                    ),
                ),
                (
                    "system_prompt",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="agent_settings_system_prompt",
                        to="server.genericcontent",
                    ),
                ),
                (
                    "task_prompt",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="agent_settings_task_prompt",
                        to="server.genericcontent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="agent_settings",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_agent_versions",
                to="server.settingsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="instanceversionmodel",
            name="instance_profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_instance_versions",
                to="server.settingsmodel",
            ),
        ),
        migrations.DeleteModel(
            name="ProfileModel",
        ),
    ]
