# Generated by Django 5.2.9 on 2026-04-04 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0010_agentprofile_enable_thinking_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentprofile",
            old_name="enable_thinking",
            new_name="thinking",
        ),
    ]
