# Generated by Django 5.2.9 on 2026-05-10 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0011_remove_agentversionmodel_agent_profile_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstanceVersionModel",
            new_name="SessionVersionModel",
        ),
        migrations.RenameField(
            model_name="sessionversionmodel",
            old_name="instance_profile",
            new_name="instance_settings",
        ),
    ]
