# Generated by Django 5.2.9 on 2026-04-05 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0011_rename_enable_thinking_agentprofile_thinking"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="message_content",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="reponse_messages",
                to="server.genericcontent",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="message_reasoning",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="reponse_reason",
                to="server.genericcontent",
            ),
        ),
    ]
