# Generated by Django 5.2.9 on 2026-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_filesystem", "0002_initial"),
        ("server", "0012_rename_instanceversionmodel_sessionversionmodel_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConversationMessage",
            new_name="Message",
        ),
        migrations.RenameModel(
            old_name="ConversationMessagePart",
            new_name="MessagePart",
        ),
        migrations.RemoveConstraint(
            model_name="messagepart",
            name="server_ConversationMessagePart_content_type_MessageContentType",
        ),
        migrations.RenameField(
            model_name="querymessage",
            old_name="conversation_message",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="querymessagepart",
            old_name="conversation_message",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="querymessagepart",
            old_name="conversation_message_part",
            new_name="message_part",
        ),
        migrations.AddConstraint(
            model_name="messagepart",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_type__in", ["IMAGE", "TEXT", "TEMPLATE"])),
                name="server_MessagePart_content_type_MessageContentType",
            ),
        ),
    ]
