# Generated by Django 5.2.9 on 2026-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0012_response_message_content_response_message_reasoning"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={"ordering": ("index", "pk")},
        ),
        migrations.AlterModelOptions(
            name="conversationmessagepart",
            options={"ordering": ("index", "pk")},
        ),
        migrations.AlterModelOptions(
            name="querymessage",
            options={"ordering": ("index", "pk")},
        ),
        migrations.AlterModelOptions(
            name="querymessagepart",
            options={"ordering": ("index", "pk")},
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="index",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="querymessage",
            name="index",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="querymessagepart",
            name="index",
            field=models.FloatField(default=0),
        ),
    ]
