# Generated by Django 5.2.9 on 2026-05-11 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0013_rename_conversationmessage_message_and_more"),
    ]

    operations = [
        
    ]
