# Generated by Django 5.2.9 on 2026-05-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0014_remove_querymessagepart_fslogentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agenttaskcall",
            old_name="agent_instance_version",
            new_name="session_version",
        ),
        migrations.RenameField(
            model_name="agenttaskinstance",
            old_name="agent_instance_version",
            new_name="session_version",
        ),
        migrations.RenameField(
            model_name="agenttaskrun",
            old_name="agent_instance_version",
            new_name="session_version",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="agent_instance_version",
            new_name="session_version",
        ),
        migrations.RenameField(
            model_name="query",
            old_name="agent_instance_version",
            new_name="session_version",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="agent_instance_version",
            new_name="session_version",
        ),
        migrations.RenameField(
            model_name="sessionversionmodel",
            old_name="instance_settings",
            new_name="session_settings",
        ),
        migrations.RemoveField(
            model_name="sessionversionmodel",
            name="child_agent_instance_versions",
        ),
        migrations.AddField(
            model_name="sessionversionmodel",
            name="child_session_versions",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="parent_session_versions",
                to="server.sessionversionmodel",
            ),
        ),
        migrations.AddField(
            model_name="sessionversionmodel",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_session_versions",
                to="server.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_session_versions",
                to="server.agentmodel",
            ),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="agent_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_session_versions",
                to="server.sessionmodel",
            ),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="agent_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_session_versions",
                to="server.agentversionmodel",
            ),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_session_versions",
                to="server.sessionversionmodel",
            ),
        ),
    ]
