# Generated by Django 5.2.9 on 2026-04-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0014_agenttaskcall_ended_at_agenttaskrun_ended_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttaskrun",
            name="taskrun_subtask_references",
            field=models.ManyToManyField(
                blank=True,
                help_text="AgentTaskCalls spawned",
                related_name="rev_taskrun_subtask_references",
                through="server.AgentTaskRunSubtask",
                through_fields=("parent", "child"),
                to="server.agenttaskcall",
            ),
        ),
    ]
