# Generated by Django 5.2.9 on 2026-05-11 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0015_rename_agent_instance_version_agenttaskcall_session_version_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionmodel",
            old_name="latest_instance_version",
            new_name="latest_session_version",
        ),
    ]
