# Generated by Django 5.2.9 on 2026-05-11 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0016_rename_latest_instance_version_sessionmodel_latest_session_version",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionmodel",
            old_name="latest_session_version",
            new_name="latest_instance_version",
        ),
    ]
