# Generated by Django 5.2.9 on 2026-05-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0017_rename_latest_session_version_sessionmodel_latest_instance_version",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settingsmodel",
            name="commit",
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="commandNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="disallowedCommandNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="disallowedSkillNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="disallowedTaskNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="disallowedToolNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="extra_settings",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="max_history_messages",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="max_retries",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="max_task_steps",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="priority",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="skillNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="taskNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="toolNames",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="unattended_steps",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
