# Generated by Django 5.2.9 on 2026-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0018_remove_settingsmodel_commit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsmodel",
            name="commit",
            field=models.TextField(default="", max_length=1024),
        ),
    ]
