# Generated by Django 5.2.9 on 2026-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0019_settingsmodel_commit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsmodel",
            name="thinking",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
