# Generated by Django 5.2.9 on 2026-05-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0020_alter_settingsmodel_thinking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsmodel",
            name="execution_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interrupt", "Interrupt"),
                    ("queue", "Queue"),
                    ("merge", "Merge"),
                    ("parallel", "Parallel"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="tool_call_syntax",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default (OpenAI style)"),
                    ("custom", "Custom tagging"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
