# Generated by Django 5.2.9 on 2026-05-11 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0021_alter_settingsmodel_execution_mode_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionmodel",
            old_name="latest_instance_version",
            new_name="latest_session_version",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="agent",
        ),
    ]
