# Generated by Django 5.2.9 on 2026-05-12 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0022_rename_latest_instance_version_sessionmodel_latest_session_version_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workspace",
            new_name="WorkspaceModel",
        ),
    ]
