# Generated by Django 5.2.9 on 2026-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0023_rename_workspace_workspacemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="message_toolcalls",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name="settingsmodel",
            name="reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interrupt", "Interrupt"),
                    ("queue", "Queue"),
                    ("merge", "Merge"),
                    ("parallel", "Parallel"),
                ],
                default="none",
                max_length=20,
                null=True,
            ),
        ),
    ]
