# Generated by Django 5.2.9 on 2026-05-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0024_response_message_toolcalls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="commit",
            field=models.TextField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="description",
            field=models.TextField(blank=True, default="", max_length=65500),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="session_settings",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_instance_versions",
                to="server.settingsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="sessionversionmodel",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_session_versions",
                to="server.workspacemodel",
            ),
        ),
        migrations.AlterField(
            model_name="settingsmodel",
            name="reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None, default"),
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Extra High"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
