# Generated by Django 5.2.9 on 2026-05-14 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0025_alter_sessionversionmodel_commit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cronjob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="", max_length=10000)),
                ("schedule", models.CharField(max_length=2048)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_cron",
                        to="server.agentmodel",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="related_cron_prompt",
                        to="server.genericcontent",
                    ),
                ),
            ],
        ),
    ]
