# Generated by Django 5.2.9 on 2026-05-14 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0026_cronjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionversionmodel",
            name="commit",
        ),
    ]
