# Generated by Django 5.2.9 on 2026-05-15 03:33

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0027_remove_sessionversionmodel_commit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentversionmodel",
            old_name="extendsAgentNames",
            new_name="extends_agent_names",
        ),
        migrations.RenameField(
            model_name="agentversionmodel",
            old_name="extendsAgentVersions",
            new_name="extends_agent_versions",
        ),
        migrations.RemoveField(
            model_name="agentversionmodel",
            name="extendsAgents",
        ),
        migrations.RemoveField(
            model_name="agentversionmodel",
            name="parent_agent",
        ),
        migrations.RemoveField(
            model_name="agentversionmodel",
            name="parent_project",
        ),
        migrations.RemoveField(
            model_name="agentversionmodel",
            name="parent_skill",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="commit",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="description",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="function_schema",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="limit_per_instance_parallel_runs",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="limit_subtask_parallel_runs",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="max_retries",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="max_subtask_error_rate",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="max_subtask_errors",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="path",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="requires_approval",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="retry_delay",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="retry_requires_approval",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="time_limit",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="trigger",
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="parent_agent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_agents",
                to="server.agentmodel",
            ),
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="parent_project",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_agents",
                to="server.project",
            ),
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="parent_skill",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_agents",
                to="server.skill",
            ),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="defined_skill_versions",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="related_agent_versions",
                to="server.skillversion",
            ),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="defined_subagent_versions",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="related_parents",
                to="server.agentversionmodel",
            ),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="hash",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="skillversion",
            name="version_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agentversionmodel",
            name="commit",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.CreateModel(
            name="TaskDefinitionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_data",
                    models.TextField(blank=True, default="", max_length=104857600),
                ),
                ("description", models.TextField()),
                ("function_schema", models.JSONField()),
                ("requires_approval", models.BooleanField(default=False)),
                ("time_limit", models.IntegerField(default=None, null=True)),
                ("max_subtask_errors", models.IntegerField(default=0)),
                ("max_subtask_error_rate", models.IntegerField(default=0)),
                ("limit_subtask_parallel_runs", models.IntegerField(default=0)),
                ("limit_per_instance_parallel_runs", models.IntegerField(default=1)),
                ("priority", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=0)),
                ("retry_delay", models.IntegerField(default=10)),
                ("retry_requires_approval", models.BooleanField(default=True)),
                (
                    "trigger",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                ("commit", models.CharField(default="", max_length=1024)),
                (
                    "fork_of",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="server.taskdefinitionversion",
                    ),
                ),
                (
                    "raw_data_reference",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_references",
                        to="server.taskdefinitionversion",
                    ),
                ),
                (
                    "task_definition",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="server.taskdefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="defined_task_versions",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="related_agent_versions",
                to="server.taskdefinitionversion",
            ),
        ),
        migrations.AddField(
            model_name="taskdefinition",
            name="latest_task_version",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_newest_task",
                to="server.taskdefinitionversion",
            ),
        ),
    ]
