# Generated by Django 5.2.9 on 2026-05-15 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "server",
            "0028_rename_extendsagentnames_agentversionmodel_extends_agent_names_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="SkillModel",
        ),
        migrations.RenameModel(
            old_name="SkillVersion",
            new_name="SkillModelVersion",
        ),
    ]
