# Generated by Django 5.2.9 on 2026-05-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0029_rename_skill_skillmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentversionmodel",
            name="extends_agent_versions",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="related_inheritors",
                to="server.agentversionmodel",
            ),
        ),
    ]
