# Generated by Django 5.2.9 on 2026-05-15 06:07

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0030_alter_agentversionmodel_extends_agent_versions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentversionmodel",
            name="extends_agent_versions",
            field=sortedm2m.fields.SortedManyToManyField(
                default=None,
                help_text=None,
                null=True,
                related_name="related_inheritors",
                to="server.agentversionmodel",
            ),
        ),
    ]
