# Generated by Django 5.2.9 on 2026-05-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0031_alter_agentversionmodel_extends_agent_versions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agenttaskcall",
            old_name="agent_instance",
            new_name="session",
        ),
        migrations.RenameField(
            model_name="sessionversionmodel",
            old_name="agent_instance",
            new_name="session",
        ),
        migrations.RenameField(
            model_name="settingsmodel",
            old_name="max_task_steps",
            new_name="max_turns",
        ),
        migrations.RenameField(
            model_name="settingsmodel",
            old_name="unattended_steps",
            new_name="max_unattended_turns",
        ),
        migrations.AddField(
            model_name="message",
            name="prev_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_messages",
                to="server.message",
            ),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="turn_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="unattended_turn_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="query",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_messages",
                to="server.query",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_messages",
                to="server.response",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="session_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_messages",
                to="server.sessionversionmodel",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="tool_calls",
            field=models.ManyToManyField(
                related_name="related_messages", to="server.agenttaskcall"
            ),
        ),
    ]
