# Generated by Django 5.2.9 on 2026-05-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0032_rename_agent_instance_agenttaskcall_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenttaskinstance",
            name="agent_task_definition",
        ),
        migrations.AddField(
            model_name="agenttaskinstance",
            name="task_definition_version",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_agent_task_instances",
                to="server.taskdefinitionversion",
            ),
        ),
    ]
