# Generated by Django 5.2.9 on 2026-05-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0034_rename_agent_instance_agenttaskinstance_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenttaskcall",
            name="agent_task_definition",
        ),
        migrations.AddField(
            model_name="agenttaskcall",
            name="task_definition_version",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_agent_task_calls",
                to="server.taskdefinitionversion",
            ),
        ),
    ]
