# Generated by Django 5.2.9 on 2026-05-15 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0036_remove_agenttaskrun_agent_task_definition_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debuglogentry",
            old_name="agent_instance",
            new_name="session",
        ),
    ]
