# Generated by Django 5.2.9 on 2026-05-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0037_rename_agent_instance_debuglogentry_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="query",
        ),
        migrations.RemoveField(
            model_name="query",
            name="aimodel",
        ),
        migrations.RemoveField(
            model_name="response",
            name="aimodel",
        ),
        migrations.RemoveField(
            model_name="response",
            name="message_content",
        ),
        migrations.RemoveField(
            model_name="response",
            name="message_reasoning",
        ),
        migrations.RemoveField(
            model_name="response",
            name="message_toolcalls",
        ),
        migrations.AddField(
            model_name="query",
            name="trigger_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_queries",
                to="server.message",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="content",
            field=models.TextField(
                blank=True, default="", max_length=500000, null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="finish_reason",
            field=models.CharField(blank=True, default="", max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="reasoning",
            field=models.TextField(
                blank=True, default="", max_length=500000, null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="reasoning_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="response",
            name="time_to_first_token",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="response",
            name="token_generation_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="response",
            name="total_time",
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name="response",
            name="tool_calls",
        ),
        migrations.DeleteModel(
            name="QueryAvailableTool",
        ),
        migrations.AddField(
            model_name="response",
            name="tool_calls",
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
