# Generated by Django 5.2.9 on 2026-05-19 01:56

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_remove_message_query_remove_query_aimodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttaskinstance',
            name='taskinstance_sub_taskinstances',
        ),
        migrations.RemoveField(
            model_name='agenttaskrun',
            name='taskrun_subtask_references',
        ),
        migrations.AddField(
            model_name='agenttaskcall',
            name='parent_taskruns',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_taskcalls', to='server.agenttaskcall'),
        ),
        migrations.AddField(
            model_name='agenttaskinstance',
            name='child_instances',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='parent_instances', to='server.agenttaskinstance'),
        ),
        migrations.AddField(
            model_name='taskdefinitionversion',
            name='child_tasks',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='parent_tasks', to='server.taskdefinitionversion'),
        ),
        migrations.AlterField(
            model_name='agentversionmodel',
            name='defined_skill_versions',
            field=models.ManyToManyField(default=None, related_name='related_agent_versions', to='server.skillmodelversion'),
        ),
        migrations.AlterField(
            model_name='agentversionmodel',
            name='defined_subagent_versions',
            field=models.ManyToManyField(default=None, related_name='related_parents', to='server.agentversionmodel'),
        ),
        migrations.AlterField(
            model_name='agentversionmodel',
            name='defined_task_versions',
            field=models.ManyToManyField(default=None, related_name='related_agent_versions', to='server.taskdefinitionversion'),
        ),
        migrations.AlterField(
            model_name='agentversionmodel',
            name='extends_agent_versions',
            field=sortedm2m.fields.SortedManyToManyField(default=None, help_text=None, related_name='related_inheritors', to='server.agentversionmodel'),
        ),
        migrations.AlterField(
            model_name='querymessage',
            name='tool_calls',
            field=models.ManyToManyField(default=None, related_name='query_messages', to='server.agenttaskcall'),
        ),
        migrations.AlterField(
            model_name='response',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sessionversionmodel',
            name='child_session_versions',
            field=models.ManyToManyField(blank=True, default=None, related_name='parent_session_versions', to='server.sessionversionmodel'),
        ),
    ]
