# Generated by Django 5.2.9 on 2026-05-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_remove_agenttaskinstance_taskinstance_sub_taskinstances_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentTaskRunSubtask',
        ),
    ]
