# Generated by Django 5.2.9 on 2026-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_delete_agenttaskrunsubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefinitionversion',
            name='bound',
            field=models.BooleanField(default=False),
        ),
    ]
