# Generated by Django 5.2.9 on 2026-05-19 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0041_taskdefinitionversion_bound"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttaskcall",
            name="task_definition",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_agent_task_calls",
                to="server.taskdefinition",
            ),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="uses_tasks",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="used_by_agent_versions",
                to="server.taskdefinitionversion",
            ),
        ),
        migrations.AddField(
            model_name="taskdefinitionversion",
            name="function_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
