# Generated by Django 6.0.5 on 2026-05-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_agenttaskcall_task_definition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenttaskcall',
            old_name='parent_taskruns',
            new_name='parent_taskrun',
        ),
    ]
