# Generated by Django 6.0.5 on 2026-05-19 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_rename_parent_taskruns_agenttaskcall_parent_taskrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttaskcall',
            name='parent_taskrun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_taskcalls', to='server.agenttaskrun'),
        ),
    ]
