# Generated by Django 5.2.9 on 2026-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0044_alter_agenttaskcall_parent_taskrun"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentversionmodel",
            old_name="uses_tasks",
            new_name="task_versions",
        ),
        migrations.RenameField(
            model_name="settingsmodel",
            old_name="execution_mode",
            new_name="scheduler_strategy",
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="task_type",
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="skill_versions",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="used_by_agent_versions",
                to="server.skillmodelversion",
            ),
        ),
        migrations.AddField(
            model_name="agentversionmodel",
            name="subagent_versions",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="used_by_agent_versions",
                to="server.agentversionmodel",
            ),
        ),
        migrations.AddField(
            model_name="taskdefinitionversion",
            name="task_execution_mode",
            field=models.CharField(
                choices=[
                    ("FUNCTION", "Function"),
                    ("SCRIPT", "Script"),
                    ("CHAIN", "Chain"),
                    ("GROUP", "Group"),
                    ("CHORD", "Chord"),
                    ("MAP", "Map"),
                ],
                default="FUNCTION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskdefinitionversion",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("COMMAND", "Command"),
                    ("TASK", "Task"),
                    ("TOOL", "Tool"),
                    ("WEBAPI", "Webapi"),
                    ("WEBVIEW", "Webview"),
                ],
                default="TOOL",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AgentTaskInstanceSubtask",
        ),
    ]
