# Generated by Django 5.2.9 on 2026-05-19 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0045_rename_uses_tasks_agentversionmodel_task_versions_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taskdefinition",
            unique_together={
                ("parent_skill", "parent_agent", "parent_project", "name")
            },
        ),
    ]
