# Generated by Django 5.2.9 on 2026-05-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_alter_taskdefinition_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdefinitionversion',
            name='trigger',
        ),
    ]
