# Generated by Django 5.2.9 on 2026-05-20 04:18

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_remove_taskdefinitionversion_trigger'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagepart',
            name='server_MessagePart_content_type_MessageContentType',
        ),
        migrations.RemoveConstraint(
            model_name='querymessagepart',
            name='server_QueryMessagePart_content_type_MessageContentType',
        ),
        migrations.AddField(
            model_name='messagepart',
            name='tool_call',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.agenttaskcall'),
        ),
        migrations.AlterField(
            model_name='messagepart',
            name='content_type',
            field=django_enum.fields.EnumCharField(choices=[('IMAGE', 'Image'), ('TEXT', 'Text'), ('JSON', 'Json'), ('TEMPLATE', 'Template')], default='TEXT', max_length=8),
        ),
        migrations.AlterField(
            model_name='querymessagepart',
            name='content_type',
            field=django_enum.fields.EnumCharField(choices=[('IMAGE', 'Image'), ('TEXT', 'Text'), ('JSON', 'Json'), ('TEMPLATE', 'Template')], default='TEXT', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='messagepart',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['IMAGE', 'TEXT', 'JSON', 'TEMPLATE'])), name='server_MessagePart_content_type_MessageContentType'),
        ),
        migrations.AddConstraint(
            model_name='querymessagepart',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['IMAGE', 'TEXT', 'JSON', 'TEMPLATE'])), name='server_QueryMessagePart_content_type_MessageContentType'),
        ),
    ]
