# Generated by Django 5.2.9 on 2026-05-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0048_remove_messagepart_server_messagepart_content_type_messagecontenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttaskrun',
            name='agent_task_instance',
        ),
    ]
