# Generated by Django 6.0.5 on 2026-05-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0049_remove_agenttaskrun_agent_task_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaskrun',
            name='agent_task_instance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agent_task_runs', to='server.agenttaskinstance'),
        ),
    ]
