# Generated by Django 5.2.9 on 2026-05-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0050_agenttaskrun_agent_task_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionversionmodel',
            old_name='agent_version',
            new_name='pinned_agent_version',
        ),
    ]
