# Generated by Django 6.0.5 on 2026-05-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0051_rename_agent_version_sessionversionmodel_pinned_agent_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionversionmodel',
            name='pinned_agent_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_session_versions', to='server.agentversionmodel'),
        ),
    ]
