# Generated by Django 6.0.5 on 2026-05-20 06:52

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0052_alter_sessionversionmodel_pinned_agent_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepart',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('reasoning', 'Reasoning'), ('message', 'Message'), ('tool call', 'Toolcall')], default='message', max_length=9),
        ),
        migrations.AddConstraint(
            model_name='messagepart',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['reasoning', 'message', 'tool call'])), name='server_MessagePart_type_MessagePartType'),
        ),
    ]
