# Generated by Django 5.2.9 on 2026-05-21 04:04

import dirtyfields.dirtyfields
import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0053_messagepart_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttaskrun',
            name='agent_task_instance',
        ),
        migrations.RemoveField(
            model_name='agenttaskcall',
            name='agent_task_instance',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagepart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='querymessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='querymessagepart',
            options={},
        ),
        migrations.RenameField(
            model_name='messagepart',
            old_name='content_template',
            new_name='template_data',
        ),
        migrations.RenameField(
            model_name='querymessagepart',
            old_name='message_part',
            new_name='source_message_part',
        ),
        migrations.RemoveField(
            model_name='message',
            name='index',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tool_calls',
        ),
        migrations.RemoveField(
            model_name='messagepart',
            name='index',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='index',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='tool_calls',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='tool_response',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='content_template',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='index',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='message',
        ),
        migrations.AddField(
            model_name='querymessage',
            name='source_message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_query_messages', to='server.message'),
        ),
        migrations.AddField(
            model_name='querymessagepart',
            name='template_data',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='query_message_parts_template_data', to='server.genericcontent'),
        ),
        migrations.AlterField(
            model_name='querymessage',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_query_messages', to='server.query'),
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.TextField(blank=True, default='', max_length=104857600)),
                ('iarguments_json', models.JSONField(default=dict, null=True)),
                ('requires_approval', models.BooleanField(default=None)),
                ('time_limit', models.IntegerField(default=None, null=True)),
                ('max_subtask_errors', models.IntegerField(default=None)),
                ('max_subtask_error_rate', models.IntegerField(default=None)),
                ('limit_subtask_parallel_runs', models.IntegerField(default=None)),
                ('limit_per_instance_parallel_runs', models.IntegerField(default=None)),
                ('priority', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=None)),
                ('retry_delay', models.IntegerField(default=None)),
                ('retry_requires_approval', models.BooleanField(default=None)),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('child_instances', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='parent_instances', to='server.taskinstance')),
                ('fork_of', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='server.taskinstance')),
                ('raw_data_reference', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='server.taskinstance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_instances', to='server.sessionmodel')),
                ('session_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task_instances', to='server.sessionversionmodel')),
                ('task_definition_version', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_instances', to='server.taskdefinitionversion')),
                ('taskinstance_arg_references', models.ManyToManyField(blank=True, help_text='AgentTaskInstances used in instance args/kwargs', related_name='rev_taskinstance_arg_references', to='server.taskinstance')),
                ('taskinstance_result_references', models.ManyToManyField(blank=True, related_name='rev_taskinstance_result_references', to='server.taskinstance')),
                ('taskinstances_after_run_hooks', models.ManyToManyField(blank=True, related_name='rev_taskinstances_hook_after_run', to='server.taskinstance')),
                ('taskinstances_before_run_hooks', models.ManyToManyField(blank=True, related_name='rev_taskinstances_hook_before_run', to='server.taskinstance')),
                ('taskinstances_on_error_callbacks', models.ManyToManyField(blank=True, related_name='rev_taskinstances_callback_on_erro', to='server.taskinstance')),
                ('taskinstances_on_success_callbacks', models.ManyToManyField(blank=True, related_name='rev_taskinstances_on_success_callbacks', to='server.taskinstance')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='agenttaskcall',
            name='task_instance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agent_task_calls', to='server.taskinstance'),
        ),
        migrations.AddField(
            model_name='agenttaskrun',
            name='task_instance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agent_task_runs', to='server.taskinstance'),
        ),
        migrations.DeleteModel(
            name='AgentTaskInstance',
        ),
    ]
