# Generated by Django 5.2.9 on 2026-05-21 09:40

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0054_remove_agenttaskrun_agent_task_instance_and_more'),
    ]

    operations = [
  
      
    ]
