# Generated by Django 5.2.9 on 2026-05-21 09:40

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0055_remove_messagepart_server_messagepart_type_messageparttype_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagepart',
            name='server_MessagePart_type_MessagePartType',
        ),
       
    ]
