# Generated by Django 5.2.9 on 2026-05-21 09:45

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0056_remove_messagepart_server_messagepart_type_messageparttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepart',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('REASONING', 'Reasoning'), ('MESSAGE', 'Message'), ('TOOLCALL', 'Toolcall')], default='MESSAGE', max_length=9),
        ),
        migrations.AddConstraint(
            model_name='messagepart',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['REASONING', 'MESSAGE', 'TOOLCALL'])), name='server_MessagePart_type_MessagePartType'),
        ),
    ]
