# Generated by Django 5.2.9 on 2026-05-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0057_alter_messagepart_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionversionmodel',
            old_name='created_by',
            new_name='parent_session_version',
        ),
        migrations.RenameField(
            model_name='sessionmodel',
            old_name='created_by',
            new_name='parent_session',
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='parent_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sessions', to='server.sessionmodel'),
        ),
        migrations.AddField(
            model_name='agentversionmodel',
            name='subagent_configs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='disallowedSubagentNames',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='subagentNames',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
