# Generated by Django 5.2.9 on 2026-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0058_rename_created_by_sessionversionmodel_parent_session_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
