# Generated by Django 5.2.9 on 2026-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0059_sessionmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='subagentResultDelivery',
            field=models.CharField(blank=True, choices=[('passive', 'Passive — results added to conversation, processed on next turn'), ('immediate', 'Immediate — inject result and trigger process_turn')], default=None, max_length=20, null=True),
        ),
    ]
