# Generated by Django 5.2.9 on 2026-05-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0060_settingsmodel_subagentresultdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionversionmodel',
            name='workingdir',
        ),
    ]
