# Generated by Django 6.0.5 on 2026-05-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0061_remove_sessionversionmodel_workingdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefinition',
            name='group_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
