# Generated by Django 5.2.9 on 2026-05-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0062_taskdefinition_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='prompt',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='function_name',
            field=models.CharField(blank=True, default='', help_text='Name of the task/tool/command to execute.', max_length=255),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='function_type',
            field=models.CharField(blank=True, choices=[('', 'Send message (ingest_user_message)'), ('task', 'Task'), ('tool', 'Tool'), ('command', 'Command')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='last_run_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='last_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_cron_message', to='server.genericcontent'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='next_run_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='session_mode',
            field=models.CharField(choices=[('new', 'New session each run'), ('existing', 'Reuse existing session')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='session_name',
            field=models.CharField(blank=True, default='', help_text='Session name for existing-session mode. Leave blank for auto-name.', max_length=255),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
    ]
