# Generated by Django 5.2.9 on 2026-05-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0063_remove_cronjob_prompt_cronjob_function_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Named Pipe',
                'verbose_name_plural': 'Named Pipes',
            },
        ),
        migrations.AddField(
            model_name='agenttaskcall',
            name='pipe_output_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='taskdefinitionversion',
            name='pipe_output_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='NamedPipeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('arguments_template', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.taskdefinitionversion')),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='server.namedpipe')),
            ],
            options={
                'verbose_name': 'Pipe Subscription',
                'verbose_name_plural': 'Pipe Subscriptions',
                'unique_together': {('pipe', 'consumer_task')},
            },
        ),
    ]
