# Generated by Django 5.2.9 on 2026-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0064_namedpipe_agenttaskcall_pipe_output_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='pipe_names',
            field=models.JSONField(blank=True, default=list, help_text='Published to these named pipes after each run.'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='pipe_output_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
