# Generated by Django 5.2.9 on 2026-05-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0065_cronjob_pipe_names_taskinstance_pipe_output_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedpipesubscription',
            name='agent',
            field=models.ForeignKey(blank=True, help_text="Agent to use for consumer task calls. Leave empty to use the task definition's default agent.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.agentmodel'),
        ),
        migrations.AddField(
            model_name='namedpipesubscription',
            name='session_mode',
            field=models.CharField(choices=[('new', 'New session each run'), ('existing', 'Reuse existing session')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='namedpipesubscription',
            name='session_name',
            field=models.CharField(blank=True, default='', help_text='Session name for existing-session mode.', max_length=255),
        ),
    ]
