# Generated by Django 6.0.5 on 2026-05-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0066_pipe_subscription_agent_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='precision',
            field=models.FloatField(blank=True, choices=[(0.05, 'Precise'), (0.2, 'Focused'), (0.55, 'Balanced'), (0.85, 'Creative'), (1.0, 'Exploratory'), (1.2, 'Experimental')], default=None, null=True),
        ),
    ]
