# Generated by Django 5.2.9 on 2026-05-27 13:40

import django.db.models.deletion
import server.models.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0067_settingsmodel_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='parent_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='server.project'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='precision',
            field=models.FloatField(blank=True, choices=server.models.settings.ResponseTemperature.choices, default=None, null=True),
        ),
    ]
