# Generated by Django 5.2.9 on 2026-05-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0068_sessionmodel_is_archived_sessionmodel_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='parent_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_crons', to='server.project'),
        ),
    ]
