# Generated by Django 5.2.9 on 2026-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0069_cronjob_parent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
