# Generated by Django 5.2.9 on 2026-05-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0070_cronjob_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='workspace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cron_jobs', to='server.workspacemodel'),
        ),
    ]
