# Generated by Django 6.0.5 on 2026-05-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0071_cronjob_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
