# Generated by Django 5.2.9 on 2026-06-03 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0072_alter_agentmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaskcall',
            name='cronjob',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_task_calls', to='server.cronjob'),
        ),
        migrations.AlterField(
            model_name='taskdefinitionversion',
            name='task_execution_mode',
            field=models.CharField(choices=[('FUNCTION', 'Function'), ('SCRIPT', 'Script'), ('CHAIN', 'Chain'), ('GROUP', 'Group'), ('MAP', 'Map')], default='FUNCTION', max_length=20),
        ),
    ]
