# Generated by Django 5.2.9 on 2026-06-07 16:47

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0073_agenttaskcall_cronjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.TextField(blank=True, default='', max_length=104857600)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('collection_type', models.CharField(choices=[('stream', 'Stream'), ('set', 'Ordered Set')], default='stream', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('processor', models.JSONField(blank=True, default=dict)),
                ('on_removed', models.JSONField(blank=True, default=dict)),
                ('member_field', models.TextField(blank=True, default='', help_text='Python expression to extract the member (unique ID) from the item')),
                ('score_field', models.TextField(blank=True, default='', help_text='Python expression to extract the score (float) from the item')),
                ('retroactive_on_source_change', models.IntegerField(default=0, help_text='When source matching criteria change, max existing items to retroactively process (0 = off)')),
                ('max_reprocess', models.IntegerField(default=0, help_text='When processor task is updated, max historical items to reprocess (0 = off)')),
                ('fork_of', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='server.datacollection')),
                ('raw_data_reference', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='server.datacollection')),
            ],
            options={
                'verbose_name': 'Data Collection',
                'verbose_name_plural': 'Data Collections',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.TextField(blank=True, default='', max_length=104857600)),
                ('member', models.CharField(max_length=1024)),
                ('score', models.FloatField(default=0.0)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('fork_of', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='server.collectionitem')),
                ('raw_data_reference', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='server.collectionitem')),
                ('source_call', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='server.agenttaskcall')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='server.datacollection')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'unique_together': {('collection', 'member')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
