# Generated by Django 5.2.9 on 2026-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0075_remove_namedpipe_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['created_at'], name='server_coll_created_45ba74_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['score'], name='server_coll_score_c6660a_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'score'], name='server_coll_collect_7844a2_idx'),
        ),
        migrations.AddIndex(
            model_name='datacollection',
            index=models.Index(fields=['is_active'], name='server_data_is_acti_523dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='datacollection',
            index=models.Index(fields=['collection_type'], name='server_data_collect_371fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='datacollection',
            index=models.Index(fields=['collection_type', 'is_active'], name='server_data_collect_b63e65_idx'),
        ),
    ]
