# Generated by Django 5.2.9 on 2026-06-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0076_collectionitem_server_coll_created_45ba74_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='source_item',
            field=models.ForeignKey(blank=True, default=None, help_text='The upstream CollectionItem whose propagation created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_items', to='server.collectionitem'),
        ),
    ]
