# Generated by Django 5.2.9 on 2026-06-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0077_collectionitem_source_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttaskcall',
            name='pipe_output_names',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='pipe_names',
        ),
        migrations.RemoveField(
            model_name='taskdefinitionversion',
            name='pipe_output_names',
        ),
        migrations.RemoveField(
            model_name='taskinstance',
            name='pipe_output_names',
        ),
    ]
