# Generated by Django 5.2.9 on 2026-06-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0078_remove_pipe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='open_weights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='self_hosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_reasoning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_tool_call',
            field=models.BooleanField(default=False),
        ),
    ]
