# Generated by Django 6.0.6 on 2026-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_rename_billion_parameters_and_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='requires_reasoning_echo',
            field=models.BooleanField(default=False),
        ),
    ]
