# Generated by Django 6.0.5 on 2026-07-01 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0081_aimodel_requires_reasoning_echo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='fork_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='server.cronjob'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='raw_data',
            field=models.TextField(blank=True, default='', max_length=104857600),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='server.cronjob'),
        ),
        migrations.AddField(
            model_name='historylimitingrule',
            name='fork_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='server.historylimitingrule'),
        ),
        migrations.AddField(
            model_name='historylimitingrule',
            name='raw_data',
            field=models.TextField(blank=True, default='', max_length=104857600),
        ),
        migrations.AddField(
            model_name='historylimitingrule',
            name='raw_data_reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_references', to='server.historylimitingrule'),
        ),
    ]
