# Generated by Django 6.0.6 on 2026-07-09 08:32

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0082_cronjob_fork_of_cronjob_raw_data_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagepart',
            name='server_MessagePart_type_MessagePartType',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='auto_compact_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='compact_size_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='messagepart',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('REASONING', 'Reasoning'), ('MESSAGE', 'Message'), ('TOOLCALL', 'Toolcall'), ('COMPACTION', 'Compaction')], default='MESSAGE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='messagepart',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['REASONING', 'MESSAGE', 'TOOLCALL', 'COMPACTION'])), name='server_MessagePart_type_MessagePartType'),
        ),
    ]
