# Generated by Django 6.0.5 on 2026-07-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0083_remove_messagepart_server_messagepart_type_messageparttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemodel',
            name='name',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='workspacemodel',
            name='path',
            field=models.CharField(max_length=4096),
        ),
    ]
