# Generated by Django 6.0.5 on 2026-07-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0085_scriptsgeneration_taskdefinition_parent_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='prev_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_messages', to='server.message'),
        ),
    ]
