# Generated by Django 6.0.5 on 2026-07-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0086_alter_message_prev_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='parent_agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_agents', to='server.agentmodel'),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='parent_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_agents', to='server.project'),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='parent_skill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_agents', to='server.skillmodel'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='parent_agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_skills', to='server.agentmodel'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='parent_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_skills', to='server.project'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='parent_skill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_skills', to='server.skillmodel'),
        ),
        migrations.AlterField(
            model_name='taskdefinition',
            name='parent_agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_definitions', to='server.agentmodel'),
        ),
        migrations.AlterField(
            model_name='taskdefinition',
            name='parent_generation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_definitions', to='server.scriptsgeneration'),
        ),
        migrations.AlterField(
            model_name='taskdefinition',
            name='parent_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_definitions', to='server.project'),
        ),
        migrations.AlterField(
            model_name='taskdefinition',
            name='parent_skill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_definitions', to='server.skillmodel'),
        ),
    ]
