# Generated by Django 6.0.5 on 2026-07-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0087_alter_agentmodel_parent_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
