# Generated by Django 6.0.5 on 2026-07-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0088_alter_agentmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaskcall',
            name='guardrail_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
