# Generated by Django 6.0.5 on 2026-07-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0089_agenttaskcall_guardrail_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttaskcall',
            name='parent_taskrun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_taskcalls', to='server.agenttaskrun'),
        ),
    ]
