# Generated by Django 6.0.5 on 2026-07-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0090_alter_agenttaskcall_parent_taskrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttaskcall',
            name='dont_start_after',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agenttaskcall',
            name='dont_start_before',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agenttaskcall',
            name='time_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
