# Generated by Django 6.0.5 on 2026-07-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0092_remove_agentmodel_fork_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmodel',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='agenttaskcall',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='agenttaskrun',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='agentversionmodel',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='apiprovider',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='debuglogentry',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='historylimitingrule',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='message',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='messagepart',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='query',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='response',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='scriptsgeneration',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='sessionmodel',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='sessionversionmodel',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='settingsmodel',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='system',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='taskdefinition',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='taskdefinitionversion',
            name='raw_data_reference',
        ),
        migrations.RemoveField(
            model_name='taskinstance',
            name='raw_data_reference',
        ),
    ]
