# Generated by Django 6.0.5 on 2026-07-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0093_remove_agentmodel_raw_data_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttaskrun',
            name='dont_start_after',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agenttaskrun',
            name='dont_start_before',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agenttaskrun',
            name='time_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
