# Generated by Django 6.0.6 on 2026-07-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0094_alter_agenttaskrun_dont_start_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaskcall',
            name='session_root_task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_child_task_calls', to='server.agenttaskcall'),
        ),
    ]
