# Generated by Django 6.0.5 on 2026-07-29 13:36

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0095_agenttaskcall_session_root_task'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='querymessage',
            name='server_QueryMessage_role_MessageRole',
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User'), ('system', 'System'), ('tool', 'Tool'), ('developer', 'Developer')], default='user', max_length=61),
        ),
        migrations.AlterField(
            model_name='querymessage',
            name='role',
            field=django_enum.fields.EnumCharField(choices=[('assistant', 'Assistant'), ('user', 'User'), ('system', 'System'), ('tool', 'Tool'), ('developer', 'Developer')], default=None, max_length=9),
        ),
        migrations.AddConstraint(
            model_name='querymessage',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['assistant', 'user', 'system', 'tool', 'developer'])), name='server_QueryMessage_role_MessageRole'),
        ),
    ]
