# Generated by Django 6.0.5 on 2026-07-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0096_remove_querymessage_server_querymessage_role_messagerole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_response', to='server.query'),
        ),
    ]
