# Generated by Django 6.0.5 on 2026-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0097_alter_response_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttaskcall',
            name='status_detail',
            field=models.CharField(choices=[('NEW', 'NEW'), ('WAITING_QUEUE', 'Waiting for execution queue'), ('WAITING_RETRY', 'Waiting for Retry time'), ('WAITING_DEPENDENCY', 'Waiting for Parent DEPENDENCY tasks'), ('WAITING_SUBTASKS_OR_HOOKS', 'Waiting for Sub-tasks'), ('WAITING_RATELIMIT', 'Waiting for Rate Limited'), ('ACTIVE_QUEUED', 'Queued'), ('ACTIVE_RUNNING', 'Running'), ('HALTED_INPUT', 'Awaiting User Input'), ('HALTED_APPROVAL', 'Awaiting User Approval'), ('HALTED_STAGNATED', 'Step Limit Reached'), ('HALTED_PAUSED', 'Paused by User'), ('ENDED_SUCCESS', 'Completed Successfully'), ('ENDED_FAILURE_EXCEPTION', 'Technical Failure'), ('ENDED_FAILURE_LOGIC', 'Logical/Quality Failure'), ('ENDED_CANCELLED', 'Cancelled before launch'), ('ENDED_STOPPED', 'Stopped after launch')], default='NEW', max_length=61),
        ),
    ]
