# Generated by Django 6.0.6 on 2026-08-03 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0101_message_session_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemodel',
            name='access',
            field=models.JSONField(blank=True, default=dict, help_text='Filesystem access policy for paths inside this workspace. Shape: {"read": {"default": "allow|ask|deny", "allow": [], "ask": [], "deny": []}, "write": {...}}. Patterns are workspace-relative globs.'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='parent_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sessions', to='server.project'),
        ),
        migrations.AlterField(
            model_name='sessionversionmodel',
            name='parent_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_session_versions', to='server.sessionmodel'),
        ),
    ]
