# Generated by Django 6.0.6 on 2026-08-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0102_workspacemodel_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefinition',
            name='access_posture',
            field=models.CharField(blank=True, choices=[('read', 'read'), ('write', 'write')], default=None, max_length=16, null=True),
        ),
    ]
