# Generated by Django 6.0.6 on 2026-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0103_taskdefinition_access_posture'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='cached_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='reasoning_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
