# Generated by Django 6.0.6 on 2026-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0104_add_response_token_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='access',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='inherit_system_prompt',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
