# Generated by Django 6.0.6 on 2026-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0105_add_access_and_inherit_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='session_type',
            field=models.CharField(choices=[('session', 'Session'), ('subsession', 'Subsession'), ('subtask_delegate', 'Subtask (delegate)'), ('subtask_fork', 'Subtask (fork)')], default='session', max_length=30),
        ),
    ]
