# Generated by Django 6.0.6 on 2026-08-04 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0106_add_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='aimodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_responses', to='server.aimodel'),
        ),
        migrations.AddField(
            model_name='response',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='response',
            name='provider_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
