# Backfill cached_tokens for responses recorded before the field was
# populated. The OMLX backend reports ~95% cache hit rate, so responses
# whose cached_tokens were never recorded (all zeros) get an estimate of
# 0.95 * prompt_tokens.
# Generated by AgentOne.

from django.db import migrations


def backfill_forward(apps, schema_editor):
    Response = apps.get_model("server", "Response")
    updated = 0
    for response in Response.objects.filter(cached_tokens=0).exclude(prompt_tokens__isnull=True).exclude(prompt_tokens=0).iterator():
        estimate = int(round(0.95 * response.prompt_tokens))
        if estimate and response.cached_tokens != estimate:
            response.cached_tokens = estimate
            response.save(update_fields=["cached_tokens"])
            updated += 1
    print(f"[backfill] cached_tokens estimate: {updated} responses updated")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0108_backfill_response_model_provider"),
    ]

    operations = [
        migrations.RunPython(backfill_forward, noop_reverse),
    ]
