# Generated by Django 6.0.6 on 2026-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0109_backfill_cached_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovider',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
