# Generated by Django 6.0.6 on 2026-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0111_backfill_provider_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
