# Generated by Django 6.0.6 on 2026-08-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0112_sessionmodel_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaskcall',
            name='auto_review_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='agenttaskcall',
            name='auto_review_status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
