# Generated by Django 6.0.5 on 2026-08-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0113_agenttaskcall_auto_review_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='tags_token_usage',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='content_postfix',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='content_prefix',
        ),
        migrations.RemoveField(
            model_name='querymessage',
            name='tags_token_usage',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='content_postfix',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='content_prefix',
        ),
        migrations.RemoveField(
            model_name='querymessagepart',
            name='tags',
        ),
    ]
