# Generated by Django 6.0.6 on 2026-08-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0114_remove_query_tags_token_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='limit_request_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='limit_tokens_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_request_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_request_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_request_per_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_tokens_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_tokens_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_tokens_per_minute',
            field=models.IntegerField(default=0),
        ),
    ]
