# Generated by Django 6.0.6 on 2026-08-15 00:09

from django.db import migrations, models


def backfill_provider_model_id(apps, schema_editor):
    """Seed ``provider_model_id`` from the old ``name`` (the raw provider id).

    Previously ``name`` held the id the provider's API expects (e.g.
    ``z-ai/glm-5.2``); it now holds the human display label.  Existing rows are
    re-keyed by the manifest loader, which re-derives both fields from
    models.yaml / providers.yaml.
    """
    AiModel = apps.get_model("server", "AiModel")
    for model in AiModel.objects.exclude(name=""):
        model.provider_model_id = model.name
        model.save(update_fields=["provider_model_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0115_aimodel_audio_aimodel_limit_request_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='self_hosted',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider_model_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.RunPython(backfill_provider_model_id, migrations.RunPython.noop),
    ]
