# Generated by Django 6.0.6 on 2026-08-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0116_remove_aimodel_self_hosted_aimodel_provider_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovider',
            name='litellm_prefix',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
