# Generated by Django 6.0.6 on 2026-08-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0117_apiprovider_litellm_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_limit_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
