# Generated by Django 6.0.6 on 2026-08-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0119_apikey_rate_limit_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='auto_failover_keys',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='max_rate_limit_wait_seconds',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='preferred_api_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_session_settings', to='server.apikey'),
        ),
    ]
