# Generated by Django 6.0.5 on 2026-08-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0120_settingsmodel_auto_failover_keys_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryLimitingRule',
        ),
    ]
