# Generated by Django 6.0.5 on 2026-09-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0122_todo_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='session_type',
            field=models.CharField(choices=[('session', 'Session'), ('subsession', 'Subsession'), ('subtask_delegate', 'Subtask (delegate)'), ('subtask_fork', 'Subtask (fork)'), ('subtask_compaczt', 'Subtask (session compaction)')], default='session', max_length=30),
        ),
    ]
