# Generated by Django 6.0.5 on 2026-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0124_settingsmodel_tool_call_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='limit_request_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='limit_request_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='limit_tokens_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='limit_tokens_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_request_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_request_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_tokens_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='limit_tokens_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
