# Generated by Django 6.0.5 on 2026-09-09 16:30

import re

from django.db import migrations, models


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")
    return slug or "provider"


def backfill_provider_slugs(apps, schema_editor):
    ApiProvider = apps.get_model("server", "ApiProvider")
    seen: set[str] = set()
    for provider in ApiProvider.objects.order_by("pk"):
        base = _slugify(provider.name)
        slug, n = base, 2
        while slug in seen:
            slug, n = f"{base}-{n}", n + 1
        seen.add(slug)
        provider.slug = slug
        provider.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0125_aimodel_limit_request_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='canonical_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='developer',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='leaderboard_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='leaderboard_rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='leaderboard_rank_is_estimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apiprovider',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.RunPython(backfill_provider_slugs, noop),
        migrations.AlterField(
            model_name='apiprovider',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
