# Generated by Django 6.0.5 on 2026-09-11 22:10

from django.db import migrations, models


def backfill_dedupe_hash(apps, schema_editor):
    """Fill dedupe_hash for rows predating the field.

    Uses TaskInstance._dedupe_hash so the stored value matches what
    TaskInstance.get_or_create() computes for the same lookup keys.
    Duplicate lookup keys were merged beforehand (rows kept: lowest pk),
    so the subsequent UniqueConstraint applies cleanly.
    """
    from server.models.tasks.task_instance import TaskInstance

    fields = ["pk", "task_definition_version_id", "session_id",
              "session_version_id", "iarguments_json"]
    fields += list(TaskInstance._LOOKUP_OPTION_FIELDS)
    total = TaskInstance.objects.count()
    batch = 2000
    updated = 0
    for start in range(0, total, batch):
        rows = list(
            TaskInstance.objects.all().order_by("pk").values(*fields)
            [start:start + batch]
        )
        objs = []
        for row in rows:
            options = {f: row[f] for f in TaskInstance._LOOKUP_OPTION_FIELDS}
            hash_value = TaskInstance._dedupe_hash(
                row["task_definition_version_id"],
                row["session_id"],
                row["session_version_id"],
                row["iarguments_json"],
                options,
            )
            objs.append(TaskInstance(pk=row["pk"], dedupe_hash=hash_value))
        TaskInstance.objects.bulk_update(objs, ["dedupe_hash"])
        updated += len(objs)
    print(f"backfilled dedupe_hash for {updated} TaskInstance rows")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0126_aimodel_canonical_id_aimodel_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='dedupe_hash',
            field=models.CharField(db_index=True, default='', help_text='SHA256 over the get_or_create lookup keys; part of the uniqueness constraint that prevents duplicate instances.', max_length=64),
        ),
        migrations.RunPython(backfill_dedupe_hash, noop_reverse),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.UniqueConstraint(fields=('task_definition_version', 'session', 'session_version', 'dedupe_hash'), name='uniq_taskinstance_dedupe'),
        ),
    ]
