# Generated by Django 6.0.5 on 2026-09-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0127_taskinstance_dedupe_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='dedupe_hash',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='SHA256 over the get_or_create lookup keys; part of the uniqueness constraint that prevents duplicate instances. NULL (e.g. ad-hoc objects.create rows) is exempt from dedup.', max_length=64, null=True),
        ),
    ]
