# Generated by Django 6.0.5 on 2026-09-21 07:31

import django_enum.fields
import server.models.workspace
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0129_workspacemodel_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='querymessage',
            name='server_QueryMessage_role_MessageRole',
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User'), ('system', 'System'), ('tool', 'Tool'), ('developer', 'Developer'), ('info', 'Info')], default='user', max_length=61),
        ),
        migrations.AlterField(
            model_name='querymessage',
            name='role',
            field=django_enum.fields.EnumCharField(choices=[('assistant', 'Assistant'), ('user', 'User'), ('system', 'System'), ('tool', 'Tool'), ('developer', 'Developer'), ('info', 'Info')], default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='workspacemodel',
            name='color',
            field=models.CharField(default=server.models.workspace.random_workspace_color, help_text='Workspace accent color as a #rrggbb hex string.', max_length=7, validators=[server.models.workspace.validate_workspace_color]),
        ),
        migrations.AddConstraint(
            model_name='querymessage',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['assistant', 'user', 'system', 'tool', 'developer', 'info'])), name='server_QueryMessage_role_MessageRole'),
        ),
    ]
