# Generated by Django 6.0.5 on 2026-09-29 14:55

import dirtyfields.dirtyfields
import django.db.models.deletion
import server.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0130_remove_querymessage_server_querymessage_role_messagerole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.TextField(blank=True, default='', max_length=104857600)),
                ('last_outcome', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='backlog', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('dispatch_count', models.IntegerField(default=0)),
                ('requires_verification', models.BooleanField(default=False)),
                ('verify_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to human'), ('skipped', 'Skipped')], default=None, max_length=20, null=True)),
                ('verify_reason', models.TextField(blank=True, default='')),
                ('verify_attempts', models.IntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='server.agentmodel')),
                ('executor_session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_work_items', to='server.sessionmodel')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_items', to='server.workitem')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='server.project')),
                ('root_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_work_items', to='server.agenttaskcall')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
            bases=(server.models.base_model.ObservableMixin, dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
