# Generated by Django 6.0.5 on 2026-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0131_workitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionmodel',
            constraint=models.UniqueConstraint(fields=('name', 'parent_session'), name='uniq_session_name_per_parent'),
        ),
    ]
