# Generated by Django 6.0.5 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0132_session_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='autoload',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='guidance_file_index_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='load_guidance_file_index',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
