# Generated by Django 6.0.5 on 2026-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0134_rename_compact_size_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentversionmodel',
            name='visibility',
            field=models.CharField(choices=[('user', 'user'), ('subagent', 'subagent'), ('internal', 'internal')], default=None, max_length=16, null=True),
        ),
    ]
