# Generated by Django 5.2.1 on 2025-10-02 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_mcp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="tool_installation",
            field=models.OneToOneField(
                blank=True,
                help_text="The ToolInstallation that manages this MCP server instance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcp_server_connection",
                to="tools_common.toolinstallation",
            ),
        ),
    ]
