# Generated by Django 5.2.1 on 2025-10-03 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools_mcp", "0002_mcpserver_tool_installation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="transport_type",
            field=models.CharField(
                choices=[
                    ("tcp", "TCP Socket (HTTP/S)"),
                    ("stdin_stdout", "Standard I/O (stdin/stdout)"),
                ],
                default="tcp",
                help_text="The communication transport type for the MCP server.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="endpoint_url",
            field=models.URLField(
                blank=True,
                help_text="The full URL of the MCP endpoint (must be HTTP or HTTPS). Required for TCP transport.",
                max_length=2000,
                null=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
    ]
