# Generated by Django 5.2.1 on 2025-10-06 01:44

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default="", max_length=104857600)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "is_remote_executor",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this system is a lightweight remote executor, not a full deployment target.",
                    ),
                ),
                (
                    "executor_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the remote executor API (e.g., http://1.2.3.4:8000).",
                        max_length=1024,
                    ),
                ),
                (
                    "executor_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for the remote executor.",
                        max_length=255,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("linux", "Linux"),
                            ("windows", "Windows"),
                            ("osx", "macOS"),
                        ],
                        default="linux",
                        help_text="The operating system of the system.",
                        max_length=10,
                    ),
                ),
                (
                    "executor_mode",
                    models.CharField(
                        choices=[
                            ("local", "Local Execution (within agent_server3 process)"),
                            ("http", "HTTP Remote Executor (FastAPI client)"),
                            (
                                "websocket",
                                "WebSocket Remote Executor (NAT-traversing client)",
                            ),
                        ],
                        default="local",
                        help_text="Determines how tool calls are executed for agent instances using this system.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
