# Generated by Django 5.2.1 on 2025-09-20 18:20

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("raw_data", models.TextField(default=b"", max_length=104857600)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "queue_name",
                    models.CharField(
                        help_text="The name of the Celery queue this system listens to.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("last_deployment_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_deployment_status",
                    models.CharField(
                        default="N/A",
                        help_text="Status of the last deployment attempt.",
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="IP address or hostname of the remote system.",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=22, help_text="SSH port."),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="Username for SSH login.", max_length=100
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Password for SSH login. Storing passwords in the database is not recommended. Use SSH keys where possible.",
                        max_length=255,
                    ),
                ),
                (
                    "ssh_key_path",
                    models.CharField(
                        blank=True,
                        help_text="Local path to the private SSH key for authentication.",
                        max_length=1024,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("linux", "Linux"),
                            ("windows", "Windows"),
                            ("osx", "macOS"),
                        ],
                        default="linux",
                        help_text="Operating system of the remote system.",
                        max_length=20,
                    ),
                ),
                (
                    "project_path",
                    models.CharField(
                        blank=True,
                        default="/opt/agent_server3",
                        help_text="Absolute path to the project directory on the remote system (e.g., /home/user/agent_server3).",
                        max_length=1024,
                    ),
                ),
                (
                    "celery_service_name",
                    models.CharField(
                        blank=True,
                        default="agent_worker",
                        help_text="Name of the Celery worker service. E.g., for systemd: 'agent_worker.service', for macOS launchd: 'com.user.agent_worker'.",
                        max_length=255,
                    ),
                ),
                (
                    "is_remote_executor",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this system is a lightweight remote executor, not a full deployment target.",
                    ),
                ),
                (
                    "executor_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the remote executor API (e.g., http://1.2.3.4:8000).",
                        max_length=1024,
                    ),
                ),
                (
                    "executor_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for the remote executor.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DeploymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="INFO", max_length=10)),
                ("message", models.TextField()),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_logs",
                        to="systems.system",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["system", "-timestamp"],
                        name="systems_dep_system__a1445a_idx",
                    )
                ],
            },
        ),
    ]
