# Generated by Django 5.2.1 on 2025-09-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="executor_mode",
            field=models.CharField(
                choices=[
                    ("local", "Local Execution (within agent_server3 process)"),
                    ("http", "HTTP Remote Executor (FastAPI client)"),
                    ("websocket", "WebSocket Remote Executor (NAT-traversing client)"),
                ],
                default="local",
                help_text="Determines how tool calls are executed for agent instances using this system.",
                max_length=20,
            ),
        ),
    ]
