# Generated by Django 5.2.1 on 2025-09-22 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0002_system_executor_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="celery_service_name",
        ),
        migrations.RemoveField(
            model_name="system",
            name="host",
        ),
        migrations.RemoveField(
            model_name="system",
            name="last_deployment_at",
        ),
        migrations.RemoveField(
            model_name="system",
            name="last_deployment_status",
        ),
        migrations.RemoveField(
            model_name="system",
            name="os",
        ),
        migrations.RemoveField(
            model_name="system",
            name="password",
        ),
        migrations.RemoveField(
            model_name="system",
            name="port",
        ),
        migrations.RemoveField(
            model_name="system",
            name="project_path",
        ),
        migrations.RemoveField(
            model_name="system",
            name="queue_name",
        ),
        migrations.RemoveField(
            model_name="system",
            name="ssh_key_path",
        ),
        migrations.RemoveField(
            model_name="system",
            name="username",
        ),
        migrations.DeleteModel(
            name="DeploymentLog",
        ),
    ]
