# Generated by Django 5.2.7 on 2025-10-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0002_alter_system_created_at_alter_system_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="fork_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forks",
                to="systems.system",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="raw_data_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_references",
                to="systems.system",
            ),
        ),
    ]
