# Generated by Django 5.2.1 on 2025-10-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "systems",
            "0003_remove_system_celery_service_name_remove_system_host_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="os",
            field=models.CharField(
                choices=[("linux", "Linux"), ("windows", "Windows"), ("osx", "macOS")],
                default="linux",
                help_text="The operating system of the system.",
                max_length=10,
            ),
        ),
    ]
