# Generated by Django 5.2.7 on 2025-10-12 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0003_system_fork_of_system_raw_data_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="is_remote_executor",
        ),
    ]
