# Generated by Django 5.2.7 on 2025-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("systems", "0004_remove_system_is_remote_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="raw_data",
            field=models.TextField(blank=True, default="", max_length=104857600),
        ),
    ]
