# Generated by Django 5.2.1 on 2025-09-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0005_alter_agentinstance_access_rules_and_more"),
        ("tools_a2a", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstancedescriptionlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="interagentmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="InstancePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "can_send",
                    models.BooleanField(
                        default=False, help_text="Source can send messages to Target"
                    ),
                ),
                (
                    "can_receive",
                    models.BooleanField(
                        default=False,
                        help_text="Source can receive messages from Target",
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_permissions",
                        to="agent.agentinstance",
                    ),
                ),
                (
                    "target_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_permissions",
                        to="agent.agentinstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("source_instance", "target_instance")},
            },
        ),
    ]
